// This file is generated by "./lib/proto/generate"

package proto

/*

Ads

A domain for ad-related metrics and data.

*/

// AdsAdFrameData Ad frame data.
type AdsAdFrameData struct {
	// FrameID The DevTools frame token.
	FrameID PageFrameID `json:"frameId"`

	// InitialOrigin (optional) The initial origin of the frame. To minimize the payload size, this is
	// only sent once per frame.
	InitialOrigin string `json:"initialOrigin,omitempty"`

	// NetworkBytes The network bytes of the frame.
	NetworkBytes float64 `json:"networkBytes"`

	// CPUTime The CPU time of the frame, in milliseconds.
	CPUTime float64 `json:"cpuTime"`
}

// AdsAdMetrics Ad metrics for a page.
type AdsAdMetrics struct {
	// ViewportAdDensityByArea The viewport ad density by area, represented as a percentage (an integer
	// between 0 and 100).
	ViewportAdDensityByArea int `json:"viewportAdDensityByArea"`

	// AverageViewportAdDensityByArea The time-weighted average of the viewport ad density by area, measured
	// across the duration of the page.
	AverageViewportAdDensityByArea float64 `json:"averageViewportAdDensityByArea"`

	// ViewportAdCount The number of ads currently visible within the viewport.
	ViewportAdCount int `json:"viewportAdCount"`

	// AverageViewportAdCount The time-weighted average of the viewport ad count, measured across the
	// duration of the page.
	AverageViewportAdCount float64 `json:"averageViewportAdCount"`

	// TotalAdCPUTime The total ad CPU usage, in milliseconds.
	TotalAdCPUTime float64 `json:"totalAdCpuTime"`

	// TotalAdNetworkBytes The total ad network bytes.
	TotalAdNetworkBytes float64 `json:"totalAdNetworkBytes"`

	// UpdateAdFrames The list of ad frames that have been updated since the last event.
	UpdateAdFrames []*AdsAdFrameData `json:"updateAdFrames"`

	// RemoveAdFrames The list of ad frame IDs that have been removed since the last event.
	RemoveAdFrames []PageFrameID `json:"removeAdFrames"`
}

// AdsGetAdMetrics Retrieves ad metrics for the current page.
type AdsGetAdMetrics struct{}

// ProtoReq name
func (m AdsGetAdMetrics) ProtoReq() string { return "Ads.getAdMetrics" }

// Call the request
func (m AdsGetAdMetrics) Call(c Client) (*AdsGetAdMetricsResult, error) {
	var res AdsGetAdMetricsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// AdsGetAdMetricsResult ...
type AdsGetAdMetricsResult struct {
	// Metrics ...
	Metrics *AdsAdMetrics `json:"metrics"`
}
