// This file is generated by "./lib/proto/generate"

package proto

/*

BluetoothEmulation

This domain allows configuring virtual Bluetooth devices to test
the web-bluetooth API.

*/

// BluetoothEmulationCentralState Indicates the various states of Central.
type BluetoothEmulationCentralState string

const (
	// BluetoothEmulationCentralStateAbsent enum const
	BluetoothEmulationCentralStateAbsent BluetoothEmulationCentralState = "absent"

	// BluetoothEmulationCentralStatePoweredOff enum const
	BluetoothEmulationCentralStatePoweredOff BluetoothEmulationCentralState = "powered-off"

	// BluetoothEmulationCentralStatePoweredOn enum const
	BluetoothEmulationCentralStatePoweredOn BluetoothEmulationCentralState = "powered-on"
)

// BluetoothEmulationGATTOperationType Indicates the various types of GATT event.
type BluetoothEmulationGATTOperationType string

const (
	// BluetoothEmulationGATTOperationTypeConnection enum const
	BluetoothEmulationGATTOperationTypeConnection BluetoothEmulationGATTOperationType = "connection"

	// BluetoothEmulationGATTOperationTypeDiscovery enum const
	BluetoothEmulationGATTOperationTypeDiscovery BluetoothEmulationGATTOperationType = "discovery"
)

// BluetoothEmulationCharacteristicWriteType Indicates the various types of characteristic write.
type BluetoothEmulationCharacteristicWriteType string

const (
	// BluetoothEmulationCharacteristicWriteTypeWriteDefaultDeprecated enum const
	BluetoothEmulationCharacteristicWriteTypeWriteDefaultDeprecated BluetoothEmulationCharacteristicWriteType = "write-default-deprecated"

	// BluetoothEmulationCharacteristicWriteTypeWriteWithResponse enum const
	BluetoothEmulationCharacteristicWriteTypeWriteWithResponse BluetoothEmulationCharacteristicWriteType = "write-with-response"

	// BluetoothEmulationCharacteristicWriteTypeWriteWithoutResponse enum const
	BluetoothEmulationCharacteristicWriteTypeWriteWithoutResponse BluetoothEmulationCharacteristicWriteType = "write-without-response"
)

// BluetoothEmulationCharacteristicOperationType Indicates the various types of characteristic operation.
type BluetoothEmulationCharacteristicOperationType string

const (
	// BluetoothEmulationCharacteristicOperationTypeRead enum const
	BluetoothEmulationCharacteristicOperationTypeRead BluetoothEmulationCharacteristicOperationType = "read"

	// BluetoothEmulationCharacteristicOperationTypeWrite enum const
	BluetoothEmulationCharacteristicOperationTypeWrite BluetoothEmulationCharacteristicOperationType = "write"

	// BluetoothEmulationCharacteristicOperationTypeSubscribeToNotifications enum const
	BluetoothEmulationCharacteristicOperationTypeSubscribeToNotifications BluetoothEmulationCharacteristicOperationType = "subscribe-to-notifications"

	// BluetoothEmulationCharacteristicOperationTypeUnsubscribeFromNotifications enum const
	BluetoothEmulationCharacteristicOperationTypeUnsubscribeFromNotifications BluetoothEmulationCharacteristicOperationType = "unsubscribe-from-notifications"
)

// BluetoothEmulationDescriptorOperationType Indicates the various types of descriptor operation.
type BluetoothEmulationDescriptorOperationType string

const (
	// BluetoothEmulationDescriptorOperationTypeRead enum const
	BluetoothEmulationDescriptorOperationTypeRead BluetoothEmulationDescriptorOperationType = "read"

	// BluetoothEmulationDescriptorOperationTypeWrite enum const
	BluetoothEmulationDescriptorOperationTypeWrite BluetoothEmulationDescriptorOperationType = "write"
)

// BluetoothEmulationManufacturerData Stores the manufacturer data
type BluetoothEmulationManufacturerData struct {
	// Key Company identifier
	// https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/company_identifiers/company_identifiers.yaml
	// https://usb.org/developers
	Key int `json:"key"`

	// Data Manufacturer-specific data (Encoded as a base64 string when passed over JSON)
	Data []byte `json:"data"`
}

// BluetoothEmulationScanRecord Stores the byte data of the advertisement packet sent by a Bluetooth device.
type BluetoothEmulationScanRecord struct {
	// Name (optional) ...
	Name string `json:"name,omitempty"`

	// Uuids (optional) ...
	Uuids []string `json:"uuids,omitempty"`

	// Appearance (optional) Stores the external appearance description of the device.
	Appearance *int `json:"appearance,omitempty"`

	// TxPower (optional) Stores the transmission power of a broadcasting device.
	TxPower *int `json:"txPower,omitempty"`

	// ManufacturerData (optional) Key is the company identifier and the value is an array of bytes of
	// manufacturer specific data.
	ManufacturerData []*BluetoothEmulationManufacturerData `json:"manufacturerData,omitempty"`
}

// BluetoothEmulationScanEntry Stores the advertisement packet information that is sent by a Bluetooth device.
type BluetoothEmulationScanEntry struct {
	// DeviceAddress ...
	DeviceAddress string `json:"deviceAddress"`

	// Rssi ...
	Rssi int `json:"rssi"`

	// ScanRecord ...
	ScanRecord *BluetoothEmulationScanRecord `json:"scanRecord"`
}

// BluetoothEmulationCharacteristicProperties Describes the properties of a characteristic. This follows Bluetooth Core
// Specification BT 4.2 Vol 3 Part G 3.3.1. Characteristic Properties.
type BluetoothEmulationCharacteristicProperties struct {
	// Broadcast (optional) ...
	Broadcast bool `json:"broadcast,omitempty"`

	// Read (optional) ...
	Read bool `json:"read,omitempty"`

	// WriteWithoutResponse (optional) ...
	WriteWithoutResponse bool `json:"writeWithoutResponse,omitempty"`

	// Write (optional) ...
	Write bool `json:"write,omitempty"`

	// Notify (optional) ...
	Notify bool `json:"notify,omitempty"`

	// Indicate (optional) ...
	Indicate bool `json:"indicate,omitempty"`

	// AuthenticatedSignedWrites (optional) ...
	AuthenticatedSignedWrites bool `json:"authenticatedSignedWrites,omitempty"`

	// ExtendedProperties (optional) ...
	ExtendedProperties bool `json:"extendedProperties,omitempty"`
}

// BluetoothEmulationEnable Enable the BluetoothEmulation domain.
type BluetoothEmulationEnable struct {
	// State of the simulated central.
	State BluetoothEmulationCentralState `json:"state"`

	// LeSupported If the simulated central supports low-energy.
	LeSupported bool `json:"leSupported"`
}

// ProtoReq name
func (m BluetoothEmulationEnable) ProtoReq() string { return "BluetoothEmulation.enable" }

// Call sends the request
func (m BluetoothEmulationEnable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationSetSimulatedCentralState Set the state of the simulated central.
type BluetoothEmulationSetSimulatedCentralState struct {
	// State of the simulated central.
	State BluetoothEmulationCentralState `json:"state"`
}

// ProtoReq name
func (m BluetoothEmulationSetSimulatedCentralState) ProtoReq() string {
	return "BluetoothEmulation.setSimulatedCentralState"
}

// Call sends the request
func (m BluetoothEmulationSetSimulatedCentralState) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationDisable Disable the BluetoothEmulation domain.
type BluetoothEmulationDisable struct{}

// ProtoReq name
func (m BluetoothEmulationDisable) ProtoReq() string { return "BluetoothEmulation.disable" }

// Call sends the request
func (m BluetoothEmulationDisable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationSimulatePreconnectedPeripheral Simulates a peripheral with |address|, |name| and |knownServiceUuids|
// that has already been connected to the system.
type BluetoothEmulationSimulatePreconnectedPeripheral struct {
	// Address ...
	Address string `json:"address"`

	// Name ...
	Name string `json:"name"`

	// ManufacturerData ...
	ManufacturerData []*BluetoothEmulationManufacturerData `json:"manufacturerData"`

	// KnownServiceUuids ...
	KnownServiceUuids []string `json:"knownServiceUuids"`
}

// ProtoReq name
func (m BluetoothEmulationSimulatePreconnectedPeripheral) ProtoReq() string {
	return "BluetoothEmulation.simulatePreconnectedPeripheral"
}

// Call sends the request
func (m BluetoothEmulationSimulatePreconnectedPeripheral) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationSimulateAdvertisement Simulates an advertisement packet described in |entry| being received by
// the central.
type BluetoothEmulationSimulateAdvertisement struct {
	// Entry ...
	Entry *BluetoothEmulationScanEntry `json:"entry"`
}

// ProtoReq name
func (m BluetoothEmulationSimulateAdvertisement) ProtoReq() string {
	return "BluetoothEmulation.simulateAdvertisement"
}

// Call sends the request
func (m BluetoothEmulationSimulateAdvertisement) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationSimulateGATTOperationResponse Simulates the response code from the peripheral with |address| for a
// GATT operation of |type|. The |code| value follows the HCI Error Codes from
// Bluetooth Core Specification Vol 2 Part D 1.3 List Of Error Codes.
type BluetoothEmulationSimulateGATTOperationResponse struct {
	// Address ...
	Address string `json:"address"`

	// Type ...
	Type BluetoothEmulationGATTOperationType `json:"type"`

	// Code ...
	Code int `json:"code"`
}

// ProtoReq name
func (m BluetoothEmulationSimulateGATTOperationResponse) ProtoReq() string {
	return "BluetoothEmulation.simulateGATTOperationResponse"
}

// Call sends the request
func (m BluetoothEmulationSimulateGATTOperationResponse) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationSimulateCharacteristicOperationResponse Simulates the response from the characteristic with |characteristicId| for a
// characteristic operation of |type|. The |code| value follows the Error
// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
// The |data| is expected to exist when simulating a successful read operation
// response.
type BluetoothEmulationSimulateCharacteristicOperationResponse struct {
	// CharacteristicID ...
	CharacteristicID string `json:"characteristicId"`

	// Type ...
	Type BluetoothEmulationCharacteristicOperationType `json:"type"`

	// Code ...
	Code int `json:"code"`

	// Data (optional) ...
	Data []byte `json:"data,omitempty"`
}

// ProtoReq name
func (m BluetoothEmulationSimulateCharacteristicOperationResponse) ProtoReq() string {
	return "BluetoothEmulation.simulateCharacteristicOperationResponse"
}

// Call sends the request
func (m BluetoothEmulationSimulateCharacteristicOperationResponse) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationSimulateDescriptorOperationResponse Simulates the response from the descriptor with |descriptorId| for a
// descriptor operation of |type|. The |code| value follows the Error
// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
// The |data| is expected to exist when simulating a successful read operation
// response.
type BluetoothEmulationSimulateDescriptorOperationResponse struct {
	// DescriptorID ...
	DescriptorID string `json:"descriptorId"`

	// Type ...
	Type BluetoothEmulationDescriptorOperationType `json:"type"`

	// Code ...
	Code int `json:"code"`

	// Data (optional) ...
	Data []byte `json:"data,omitempty"`
}

// ProtoReq name
func (m BluetoothEmulationSimulateDescriptorOperationResponse) ProtoReq() string {
	return "BluetoothEmulation.simulateDescriptorOperationResponse"
}

// Call sends the request
func (m BluetoothEmulationSimulateDescriptorOperationResponse) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationAddService Adds a service with |serviceUuid| to the peripheral with |address|.
type BluetoothEmulationAddService struct {
	// Address ...
	Address string `json:"address"`

	// ServiceUUID ...
	ServiceUUID string `json:"serviceUuid"`
}

// ProtoReq name
func (m BluetoothEmulationAddService) ProtoReq() string { return "BluetoothEmulation.addService" }

// Call the request
func (m BluetoothEmulationAddService) Call(c Client) (*BluetoothEmulationAddServiceResult, error) {
	var res BluetoothEmulationAddServiceResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BluetoothEmulationAddServiceResult ...
type BluetoothEmulationAddServiceResult struct {
	// ServiceID An identifier that uniquely represents this service.
	ServiceID string `json:"serviceId"`
}

// BluetoothEmulationRemoveService Removes the service respresented by |serviceId| from the simulated central.
type BluetoothEmulationRemoveService struct {
	// ServiceID ...
	ServiceID string `json:"serviceId"`
}

// ProtoReq name
func (m BluetoothEmulationRemoveService) ProtoReq() string { return "BluetoothEmulation.removeService" }

// Call sends the request
func (m BluetoothEmulationRemoveService) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationAddCharacteristic Adds a characteristic with |characteristicUuid| and |properties| to the
// service represented by |serviceId|.
type BluetoothEmulationAddCharacteristic struct {
	// ServiceID ...
	ServiceID string `json:"serviceId"`

	// CharacteristicUUID ...
	CharacteristicUUID string `json:"characteristicUuid"`

	// Properties ...
	Properties *BluetoothEmulationCharacteristicProperties `json:"properties"`
}

// ProtoReq name
func (m BluetoothEmulationAddCharacteristic) ProtoReq() string {
	return "BluetoothEmulation.addCharacteristic"
}

// Call the request
func (m BluetoothEmulationAddCharacteristic) Call(c Client) (*BluetoothEmulationAddCharacteristicResult, error) {
	var res BluetoothEmulationAddCharacteristicResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BluetoothEmulationAddCharacteristicResult ...
type BluetoothEmulationAddCharacteristicResult struct {
	// CharacteristicID An identifier that uniquely represents this characteristic.
	CharacteristicID string `json:"characteristicId"`
}

// BluetoothEmulationRemoveCharacteristic Removes the characteristic respresented by |characteristicId| from the
// simulated central.
type BluetoothEmulationRemoveCharacteristic struct {
	// CharacteristicID ...
	CharacteristicID string `json:"characteristicId"`
}

// ProtoReq name
func (m BluetoothEmulationRemoveCharacteristic) ProtoReq() string {
	return "BluetoothEmulation.removeCharacteristic"
}

// Call sends the request
func (m BluetoothEmulationRemoveCharacteristic) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationAddDescriptor Adds a descriptor with |descriptorUuid| to the characteristic respresented
// by |characteristicId|.
type BluetoothEmulationAddDescriptor struct {
	// CharacteristicID ...
	CharacteristicID string `json:"characteristicId"`

	// DescriptorUUID ...
	DescriptorUUID string `json:"descriptorUuid"`
}

// ProtoReq name
func (m BluetoothEmulationAddDescriptor) ProtoReq() string { return "BluetoothEmulation.addDescriptor" }

// Call the request
func (m BluetoothEmulationAddDescriptor) Call(c Client) (*BluetoothEmulationAddDescriptorResult, error) {
	var res BluetoothEmulationAddDescriptorResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BluetoothEmulationAddDescriptorResult ...
type BluetoothEmulationAddDescriptorResult struct {
	// DescriptorID An identifier that uniquely represents this descriptor.
	DescriptorID string `json:"descriptorId"`
}

// BluetoothEmulationRemoveDescriptor Removes the descriptor with |descriptorId| from the simulated central.
type BluetoothEmulationRemoveDescriptor struct {
	// DescriptorID ...
	DescriptorID string `json:"descriptorId"`
}

// ProtoReq name
func (m BluetoothEmulationRemoveDescriptor) ProtoReq() string {
	return "BluetoothEmulation.removeDescriptor"
}

// Call sends the request
func (m BluetoothEmulationRemoveDescriptor) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationSimulateGATTDisconnection Simulates a GATT disconnection from the peripheral with |address|.
type BluetoothEmulationSimulateGATTDisconnection struct {
	// Address ...
	Address string `json:"address"`
}

// ProtoReq name
func (m BluetoothEmulationSimulateGATTDisconnection) ProtoReq() string {
	return "BluetoothEmulation.simulateGATTDisconnection"
}

// Call sends the request
func (m BluetoothEmulationSimulateGATTDisconnection) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BluetoothEmulationGattOperationReceived Event for when a GATT operation of |type| to the peripheral with |address|
// happened.
type BluetoothEmulationGattOperationReceived struct {
	// Address ...
	Address string `json:"address"`

	// Type ...
	Type BluetoothEmulationGATTOperationType `json:"type"`
}

// ProtoEvent name
func (evt BluetoothEmulationGattOperationReceived) ProtoEvent() string {
	return "BluetoothEmulation.gattOperationReceived"
}

// BluetoothEmulationCharacteristicOperationReceived Event for when a characteristic operation of |type| to the characteristic
// respresented by |characteristicId| happened. |data| and |writeType| is
// expected to exist when |type| is write.
type BluetoothEmulationCharacteristicOperationReceived struct {
	// CharacteristicID ...
	CharacteristicID string `json:"characteristicId"`

	// Type ...
	Type BluetoothEmulationCharacteristicOperationType `json:"type"`

	// Data (optional) ...
	Data []byte `json:"data,omitempty"`

	// WriteType (optional) ...
	WriteType BluetoothEmulationCharacteristicWriteType `json:"writeType,omitempty"`
}

// ProtoEvent name
func (evt BluetoothEmulationCharacteristicOperationReceived) ProtoEvent() string {
	return "BluetoothEmulation.characteristicOperationReceived"
}

// BluetoothEmulationDescriptorOperationReceived Event for when a descriptor operation of |type| to the descriptor
// respresented by |descriptorId| happened. |data| is expected to exist when
// |type| is write.
type BluetoothEmulationDescriptorOperationReceived struct {
	// DescriptorID ...
	DescriptorID string `json:"descriptorId"`

	// Type ...
	Type BluetoothEmulationDescriptorOperationType `json:"type"`

	// Data (optional) ...
	Data []byte `json:"data,omitempty"`
}

// ProtoEvent name
func (evt BluetoothEmulationDescriptorOperationReceived) ProtoEvent() string {
	return "BluetoothEmulation.descriptorOperationReceived"
}
