// This file is generated by "./lib/proto/generate"

package proto

/*

Browser

The Browser domain defines methods and events for browser managing.

*/

// BrowserBrowserContextID (experimental) ...
type BrowserBrowserContextID string

// BrowserWindowID (experimental) ...
type BrowserWindowID int

// BrowserWindowState (experimental) The state of the browser window.
type BrowserWindowState string

const (
	// BrowserWindowStateNormal enum const
	BrowserWindowStateNormal BrowserWindowState = "normal"

	// BrowserWindowStateMinimized enum const
	BrowserWindowStateMinimized BrowserWindowState = "minimized"

	// BrowserWindowStateMaximized enum const
	BrowserWindowStateMaximized BrowserWindowState = "maximized"

	// BrowserWindowStateFullscreen enum const
	BrowserWindowStateFullscreen BrowserWindowState = "fullscreen"
)

// BrowserBounds (experimental) Browser window bounds information
type BrowserBounds struct {
	// Left (optional) The offset from the left edge of the screen to the window in pixels.
	Left *int `json:"left,omitempty"`

	// Top (optional) The offset from the top edge of the screen to the window in pixels.
	Top *int `json:"top,omitempty"`

	// Width (optional) The window width in pixels.
	Width *int `json:"width,omitempty"`

	// Height (optional) The window height in pixels.
	Height *int `json:"height,omitempty"`

	// WindowState (optional) The window state. Default to normal.
	WindowState BrowserWindowState `json:"windowState,omitempty"`
}

// BrowserPermissionType (experimental) ...
type BrowserPermissionType string

const (
	// BrowserPermissionTypeAr enum const
	BrowserPermissionTypeAr BrowserPermissionType = "ar"

	// BrowserPermissionTypeAudioCapture enum const
	BrowserPermissionTypeAudioCapture BrowserPermissionType = "audioCapture"

	// BrowserPermissionTypeAutomaticFullscreen enum const
	BrowserPermissionTypeAutomaticFullscreen BrowserPermissionType = "automaticFullscreen"

	// BrowserPermissionTypeBackgroundFetch enum const
	BrowserPermissionTypeBackgroundFetch BrowserPermissionType = "backgroundFetch"

	// BrowserPermissionTypeBackgroundSync enum const
	BrowserPermissionTypeBackgroundSync BrowserPermissionType = "backgroundSync"

	// BrowserPermissionTypeCameraPanTiltZoom enum const
	BrowserPermissionTypeCameraPanTiltZoom BrowserPermissionType = "cameraPanTiltZoom"

	// BrowserPermissionTypeCapturedSurfaceControl enum const
	BrowserPermissionTypeCapturedSurfaceControl BrowserPermissionType = "capturedSurfaceControl"

	// BrowserPermissionTypeClipboardReadWrite enum const
	BrowserPermissionTypeClipboardReadWrite BrowserPermissionType = "clipboardReadWrite"

	// BrowserPermissionTypeClipboardSanitizedWrite enum const
	BrowserPermissionTypeClipboardSanitizedWrite BrowserPermissionType = "clipboardSanitizedWrite"

	// BrowserPermissionTypeDisplayCapture enum const
	BrowserPermissionTypeDisplayCapture BrowserPermissionType = "displayCapture"

	// BrowserPermissionTypeDurableStorage enum const
	BrowserPermissionTypeDurableStorage BrowserPermissionType = "durableStorage"

	// BrowserPermissionTypeGeolocation enum const
	BrowserPermissionTypeGeolocation BrowserPermissionType = "geolocation"

	// BrowserPermissionTypeHandTracking enum const
	BrowserPermissionTypeHandTracking BrowserPermissionType = "handTracking"

	// BrowserPermissionTypeIdleDetection enum const
	BrowserPermissionTypeIdleDetection BrowserPermissionType = "idleDetection"

	// BrowserPermissionTypeKeyboardLock enum const
	BrowserPermissionTypeKeyboardLock BrowserPermissionType = "keyboardLock"

	// BrowserPermissionTypeLocalFonts enum const
	BrowserPermissionTypeLocalFonts BrowserPermissionType = "localFonts"

	// BrowserPermissionTypeLocalNetwork enum const
	BrowserPermissionTypeLocalNetwork BrowserPermissionType = "localNetwork"

	// BrowserPermissionTypeLocalNetworkAccess enum const
	BrowserPermissionTypeLocalNetworkAccess BrowserPermissionType = "localNetworkAccess"

	// BrowserPermissionTypeLoopbackNetwork enum const
	BrowserPermissionTypeLoopbackNetwork BrowserPermissionType = "loopbackNetwork"

	// BrowserPermissionTypeMidi enum const
	BrowserPermissionTypeMidi BrowserPermissionType = "midi"

	// BrowserPermissionTypeMidiSysex enum const
	BrowserPermissionTypeMidiSysex BrowserPermissionType = "midiSysex"

	// BrowserPermissionTypeNfc enum const
	BrowserPermissionTypeNfc BrowserPermissionType = "nfc"

	// BrowserPermissionTypeNotifications enum const
	BrowserPermissionTypeNotifications BrowserPermissionType = "notifications"

	// BrowserPermissionTypePaymentHandler enum const
	BrowserPermissionTypePaymentHandler BrowserPermissionType = "paymentHandler"

	// BrowserPermissionTypePeriodicBackgroundSync enum const
	BrowserPermissionTypePeriodicBackgroundSync BrowserPermissionType = "periodicBackgroundSync"

	// BrowserPermissionTypePointerLock enum const
	BrowserPermissionTypePointerLock BrowserPermissionType = "pointerLock"

	// BrowserPermissionTypeProtectedMediaIdentifier enum const
	BrowserPermissionTypeProtectedMediaIdentifier BrowserPermissionType = "protectedMediaIdentifier"

	// BrowserPermissionTypeSensors enum const
	BrowserPermissionTypeSensors BrowserPermissionType = "sensors"

	// BrowserPermissionTypeSmartCard enum const
	BrowserPermissionTypeSmartCard BrowserPermissionType = "smartCard"

	// BrowserPermissionTypeSpeakerSelection enum const
	BrowserPermissionTypeSpeakerSelection BrowserPermissionType = "speakerSelection"

	// BrowserPermissionTypeStorageAccess enum const
	BrowserPermissionTypeStorageAccess BrowserPermissionType = "storageAccess"

	// BrowserPermissionTypeTopLevelStorageAccess enum const
	BrowserPermissionTypeTopLevelStorageAccess BrowserPermissionType = "topLevelStorageAccess"

	// BrowserPermissionTypeVideoCapture enum const
	BrowserPermissionTypeVideoCapture BrowserPermissionType = "videoCapture"

	// BrowserPermissionTypeVr enum const
	BrowserPermissionTypeVr BrowserPermissionType = "vr"

	// BrowserPermissionTypeWakeLockScreen enum const
	BrowserPermissionTypeWakeLockScreen BrowserPermissionType = "wakeLockScreen"

	// BrowserPermissionTypeWakeLockSystem enum const
	BrowserPermissionTypeWakeLockSystem BrowserPermissionType = "wakeLockSystem"

	// BrowserPermissionTypeWebAppInstallation enum const
	BrowserPermissionTypeWebAppInstallation BrowserPermissionType = "webAppInstallation"

	// BrowserPermissionTypeWebPrinting enum const
	BrowserPermissionTypeWebPrinting BrowserPermissionType = "webPrinting"

	// BrowserPermissionTypeWindowManagement enum const
	BrowserPermissionTypeWindowManagement BrowserPermissionType = "windowManagement"
)

// BrowserPermissionSetting (experimental) ...
type BrowserPermissionSetting string

const (
	// BrowserPermissionSettingGranted enum const
	BrowserPermissionSettingGranted BrowserPermissionSetting = "granted"

	// BrowserPermissionSettingDenied enum const
	BrowserPermissionSettingDenied BrowserPermissionSetting = "denied"

	// BrowserPermissionSettingPrompt enum const
	BrowserPermissionSettingPrompt BrowserPermissionSetting = "prompt"
)

// BrowserPermissionDescriptor (experimental) Definition of PermissionDescriptor defined in the Permissions API:
// https://w3c.github.io/permissions/#dom-permissiondescriptor.
type BrowserPermissionDescriptor struct {
	// Name of permission.
	// See https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/permissions/permission_descriptor.idl for valid permission names.
	Name string `json:"name"`

	// Sysex (optional) For "midi" permission, may also specify sysex control.
	Sysex bool `json:"sysex,omitempty"`

	// UserVisibleOnly (optional) For "push" permission, may specify userVisibleOnly.
	// Note that userVisibleOnly = true is the only currently supported type.
	UserVisibleOnly bool `json:"userVisibleOnly,omitempty"`

	// AllowWithoutSanitization (optional) For "clipboard" permission, may specify allowWithoutSanitization.
	AllowWithoutSanitization bool `json:"allowWithoutSanitization,omitempty"`

	// AllowWithoutGesture (optional) For "fullscreen" permission, must specify allowWithoutGesture:true.
	AllowWithoutGesture bool `json:"allowWithoutGesture,omitempty"`

	// PanTiltZoom (optional) For "camera" permission, may specify panTiltZoom.
	PanTiltZoom bool `json:"panTiltZoom,omitempty"`
}

// BrowserBrowserCommandID (experimental) Browser command ids used by executeBrowserCommand.
type BrowserBrowserCommandID string

const (
	// BrowserBrowserCommandIDOpenTabSearch enum const
	BrowserBrowserCommandIDOpenTabSearch BrowserBrowserCommandID = "openTabSearch"

	// BrowserBrowserCommandIDCloseTabSearch enum const
	BrowserBrowserCommandIDCloseTabSearch BrowserBrowserCommandID = "closeTabSearch"

	// BrowserBrowserCommandIDOpenGlic enum const
	BrowserBrowserCommandIDOpenGlic BrowserBrowserCommandID = "openGlic"
)

// BrowserBucket (experimental) Chrome histogram bucket.
type BrowserBucket struct {
	// Low Minimum value (inclusive).
	Low int `json:"low"`

	// High Maximum value (exclusive).
	High int `json:"high"`

	// Count Number of samples.
	Count int `json:"count"`
}

// BrowserHistogram (experimental) Chrome histogram.
type BrowserHistogram struct {
	// Name.
	Name string `json:"name"`

	// Sum of sample values.
	Sum int `json:"sum"`

	// Count Total number of samples.
	Count int `json:"count"`

	// Buckets.
	Buckets []*BrowserBucket `json:"buckets"`
}

// BrowserPrivacySandboxAPI (experimental) ...
type BrowserPrivacySandboxAPI string

const (
	// BrowserPrivacySandboxAPIBiddingAndAuctionServices enum const
	BrowserPrivacySandboxAPIBiddingAndAuctionServices BrowserPrivacySandboxAPI = "BiddingAndAuctionServices"

	// BrowserPrivacySandboxAPITrustedKeyValue enum const
	BrowserPrivacySandboxAPITrustedKeyValue BrowserPrivacySandboxAPI = "TrustedKeyValue"
)

// BrowserSetPermission (experimental) Set permission settings for given embedding and embedded origins.
type BrowserSetPermission struct {
	// Permission Descriptor of permission to override.
	Permission *BrowserPermissionDescriptor `json:"permission"`

	// Setting of the permission.
	Setting BrowserPermissionSetting `json:"setting"`

	// Origin (optional) Embedding origin the permission applies to, all origins if not specified.
	Origin string `json:"origin,omitempty"`

	// EmbeddedOrigin (optional) Embedded origin the permission applies to. It is ignored unless the embedding origin is
	// present and valid. If the embedding origin is provided but the embedded origin isn't, the
	// embedding origin is used as the embedded origin.
	EmbeddedOrigin string `json:"embeddedOrigin,omitempty"`

	// BrowserContextID (optional) Context to override. When omitted, default browser context is used.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m BrowserSetPermission) ProtoReq() string { return "Browser.setPermission" }

// Call sends the request
func (m BrowserSetPermission) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserGrantPermissions (deprecated) (experimental) Grant specific permissions to the given origin and reject all others. Deprecated. Use
// setPermission instead.
type BrowserGrantPermissions struct {
	// Permissions ...
	Permissions []BrowserPermissionType `json:"permissions"`

	// Origin (optional) Origin the permission applies to, all origins if not specified.
	Origin string `json:"origin,omitempty"`

	// BrowserContextID (optional) BrowserContext to override permissions. When omitted, default browser context is used.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m BrowserGrantPermissions) ProtoReq() string { return "Browser.grantPermissions" }

// Call sends the request
func (m BrowserGrantPermissions) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserResetPermissions Reset all permission management for all origins.
type BrowserResetPermissions struct {
	// BrowserContextID (optional) BrowserContext to reset permissions. When omitted, default browser context is used.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m BrowserResetPermissions) ProtoReq() string { return "Browser.resetPermissions" }

// Call sends the request
func (m BrowserResetPermissions) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserSetDownloadBehaviorBehavior enum
type BrowserSetDownloadBehaviorBehavior string

const (
	// BrowserSetDownloadBehaviorBehaviorDeny enum const
	BrowserSetDownloadBehaviorBehaviorDeny BrowserSetDownloadBehaviorBehavior = "deny"

	// BrowserSetDownloadBehaviorBehaviorAllow enum const
	BrowserSetDownloadBehaviorBehaviorAllow BrowserSetDownloadBehaviorBehavior = "allow"

	// BrowserSetDownloadBehaviorBehaviorAllowAndName enum const
	BrowserSetDownloadBehaviorBehaviorAllowAndName BrowserSetDownloadBehaviorBehavior = "allowAndName"

	// BrowserSetDownloadBehaviorBehaviorDefault enum const
	BrowserSetDownloadBehaviorBehaviorDefault BrowserSetDownloadBehaviorBehavior = "default"
)

// BrowserSetDownloadBehavior (experimental) Set the behavior when downloading a file.
type BrowserSetDownloadBehavior struct {
	// Behavior Whether to allow all or deny all download requests, or use default Chrome behavior if
	// available (otherwise deny). |allowAndName| allows download and names files according to
	// their download guids.
	Behavior BrowserSetDownloadBehaviorBehavior `json:"behavior"`

	// BrowserContextID (optional) BrowserContext to set download behavior. When omitted, default browser context is used.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`

	// DownloadPath (optional) The default path to save downloaded files to. This is required if behavior is set to 'allow'
	// or 'allowAndName'.
	DownloadPath string `json:"downloadPath,omitempty"`

	// EventsEnabled (optional) Whether to emit download events (defaults to false).
	EventsEnabled bool `json:"eventsEnabled,omitempty"`
}

// ProtoReq name
func (m BrowserSetDownloadBehavior) ProtoReq() string { return "Browser.setDownloadBehavior" }

// Call sends the request
func (m BrowserSetDownloadBehavior) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserCancelDownload (experimental) Cancel a download if in progress
type BrowserCancelDownload struct {
	// GUID Global unique identifier of the download.
	GUID string `json:"guid"`

	// BrowserContextID (optional) BrowserContext to perform the action in. When omitted, default browser context is used.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m BrowserCancelDownload) ProtoReq() string { return "Browser.cancelDownload" }

// Call sends the request
func (m BrowserCancelDownload) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserClose Close browser gracefully.
type BrowserClose struct{}

// ProtoReq name
func (m BrowserClose) ProtoReq() string { return "Browser.close" }

// Call sends the request
func (m BrowserClose) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserCrash (experimental) Crashes browser on the main thread.
type BrowserCrash struct{}

// ProtoReq name
func (m BrowserCrash) ProtoReq() string { return "Browser.crash" }

// Call sends the request
func (m BrowserCrash) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserCrashGpuProcess (experimental) Crashes GPU process.
type BrowserCrashGpuProcess struct{}

// ProtoReq name
func (m BrowserCrashGpuProcess) ProtoReq() string { return "Browser.crashGpuProcess" }

// Call sends the request
func (m BrowserCrashGpuProcess) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserGetVersion Returns version information.
type BrowserGetVersion struct{}

// ProtoReq name
func (m BrowserGetVersion) ProtoReq() string { return "Browser.getVersion" }

// Call the request
func (m BrowserGetVersion) Call(c Client) (*BrowserGetVersionResult, error) {
	var res BrowserGetVersionResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BrowserGetVersionResult ...
type BrowserGetVersionResult struct {
	// ProtocolVersion Protocol version.
	ProtocolVersion string `json:"protocolVersion"`

	// Product name.
	Product string `json:"product"`

	// Revision Product revision.
	Revision string `json:"revision"`

	// UserAgent User-Agent.
	UserAgent string `json:"userAgent"`

	// JsVersion V8 version.
	JsVersion string `json:"jsVersion"`
}

// BrowserGetBrowserCommandLine (experimental) Returns the command line switches for the browser process if, and only if
// --enable-automation is on the commandline.
type BrowserGetBrowserCommandLine struct{}

// ProtoReq name
func (m BrowserGetBrowserCommandLine) ProtoReq() string { return "Browser.getBrowserCommandLine" }

// Call the request
func (m BrowserGetBrowserCommandLine) Call(c Client) (*BrowserGetBrowserCommandLineResult, error) {
	var res BrowserGetBrowserCommandLineResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BrowserGetBrowserCommandLineResult (experimental) ...
type BrowserGetBrowserCommandLineResult struct {
	// Arguments Commandline parameters
	Arguments []string `json:"arguments"`
}

// BrowserGetHistograms (experimental) Get Chrome histograms.
type BrowserGetHistograms struct {
	// Query (optional) Requested substring in name. Only histograms which have query as a
	// substring in their name are extracted. An empty or absent query returns
	// all histograms.
	Query string `json:"query,omitempty"`

	// Delta (optional) If true, retrieve delta since last delta call.
	Delta bool `json:"delta,omitempty"`
}

// ProtoReq name
func (m BrowserGetHistograms) ProtoReq() string { return "Browser.getHistograms" }

// Call the request
func (m BrowserGetHistograms) Call(c Client) (*BrowserGetHistogramsResult, error) {
	var res BrowserGetHistogramsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BrowserGetHistogramsResult (experimental) ...
type BrowserGetHistogramsResult struct {
	// Histograms.
	Histograms []*BrowserHistogram `json:"histograms"`
}

// BrowserGetHistogram (experimental) Get a Chrome histogram by name.
type BrowserGetHistogram struct {
	// Name Requested histogram name.
	Name string `json:"name"`

	// Delta (optional) If true, retrieve delta since last delta call.
	Delta bool `json:"delta,omitempty"`
}

// ProtoReq name
func (m BrowserGetHistogram) ProtoReq() string { return "Browser.getHistogram" }

// Call the request
func (m BrowserGetHistogram) Call(c Client) (*BrowserGetHistogramResult, error) {
	var res BrowserGetHistogramResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BrowserGetHistogramResult (experimental) ...
type BrowserGetHistogramResult struct {
	// Histogram.
	Histogram *BrowserHistogram `json:"histogram"`
}

// BrowserGetWindowBounds (experimental) Get position and size of the browser window.
type BrowserGetWindowBounds struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`
}

// ProtoReq name
func (m BrowserGetWindowBounds) ProtoReq() string { return "Browser.getWindowBounds" }

// Call the request
func (m BrowserGetWindowBounds) Call(c Client) (*BrowserGetWindowBoundsResult, error) {
	var res BrowserGetWindowBoundsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BrowserGetWindowBoundsResult (experimental) ...
type BrowserGetWindowBoundsResult struct {
	// Bounds information of the window. When window state is 'minimized', the restored window
	// position and size are returned.
	Bounds *BrowserBounds `json:"bounds"`
}

// BrowserGetWindowForTarget (experimental) Get the browser window that contains the devtools target.
type BrowserGetWindowForTarget struct {
	// TargetID (optional) Devtools agent host id. If called as a part of the session, associated targetId is used.
	TargetID TargetTargetID `json:"targetId,omitempty"`
}

// ProtoReq name
func (m BrowserGetWindowForTarget) ProtoReq() string { return "Browser.getWindowForTarget" }

// Call the request
func (m BrowserGetWindowForTarget) Call(c Client) (*BrowserGetWindowForTargetResult, error) {
	var res BrowserGetWindowForTargetResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// BrowserGetWindowForTargetResult (experimental) ...
type BrowserGetWindowForTargetResult struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`

	// Bounds information of the window. When window state is 'minimized', the restored window
	// position and size are returned.
	Bounds *BrowserBounds `json:"bounds"`
}

// BrowserSetWindowBounds (experimental) Set position and/or size of the browser window.
type BrowserSetWindowBounds struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`

	// Bounds New window bounds. The 'minimized', 'maximized' and 'fullscreen' states cannot be combined
	// with 'left', 'top', 'width' or 'height'. Leaves unspecified fields unchanged.
	Bounds *BrowserBounds `json:"bounds"`
}

// ProtoReq name
func (m BrowserSetWindowBounds) ProtoReq() string { return "Browser.setWindowBounds" }

// Call sends the request
func (m BrowserSetWindowBounds) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserSetContentsSize (experimental) Set size of the browser contents resizing browser window as necessary.
type BrowserSetContentsSize struct {
	// WindowID Browser window id.
	WindowID BrowserWindowID `json:"windowId"`

	// Width (optional) The window contents width in DIP. Assumes current width if omitted.
	// Must be specified if 'height' is omitted.
	Width *int `json:"width,omitempty"`

	// Height (optional) The window contents height in DIP. Assumes current height if omitted.
	// Must be specified if 'width' is omitted.
	Height *int `json:"height,omitempty"`
}

// ProtoReq name
func (m BrowserSetContentsSize) ProtoReq() string { return "Browser.setContentsSize" }

// Call sends the request
func (m BrowserSetContentsSize) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserSetDockTile (experimental) Set dock tile details, platform-specific.
type BrowserSetDockTile struct {
	// BadgeLabel (optional) ...
	BadgeLabel string `json:"badgeLabel,omitempty"`

	// Image (optional) Png encoded image. (Encoded as a base64 string when passed over JSON)
	Image []byte `json:"image,omitempty"`
}

// ProtoReq name
func (m BrowserSetDockTile) ProtoReq() string { return "Browser.setDockTile" }

// Call sends the request
func (m BrowserSetDockTile) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserExecuteBrowserCommand (experimental) Invoke custom browser commands used by telemetry.
type BrowserExecuteBrowserCommand struct {
	// CommandID ...
	CommandID BrowserBrowserCommandID `json:"commandId"`
}

// ProtoReq name
func (m BrowserExecuteBrowserCommand) ProtoReq() string { return "Browser.executeBrowserCommand" }

// Call sends the request
func (m BrowserExecuteBrowserCommand) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserAddPrivacySandboxEnrollmentOverride Allows a site to use privacy sandbox features that require enrollment
// without the site actually being enrolled. Only supported on page targets.
type BrowserAddPrivacySandboxEnrollmentOverride struct {
	// URL ...
	URL string `json:"url"`
}

// ProtoReq name
func (m BrowserAddPrivacySandboxEnrollmentOverride) ProtoReq() string {
	return "Browser.addPrivacySandboxEnrollmentOverride"
}

// Call sends the request
func (m BrowserAddPrivacySandboxEnrollmentOverride) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserAddPrivacySandboxCoordinatorKeyConfig Configures encryption keys used with a given privacy sandbox API to talk
// to a trusted coordinator.  Since this is intended for test automation only,
// coordinatorOrigin must be a .test domain. No existing coordinator
// configuration for the origin may exist.
type BrowserAddPrivacySandboxCoordinatorKeyConfig struct {
	// API ...
	API BrowserPrivacySandboxAPI `json:"api"`

	// CoordinatorOrigin ...
	CoordinatorOrigin string `json:"coordinatorOrigin"`

	// KeyConfig ...
	KeyConfig string `json:"keyConfig"`

	// BrowserContextID (optional) BrowserContext to perform the action in. When omitted, default browser
	// context is used.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m BrowserAddPrivacySandboxCoordinatorKeyConfig) ProtoReq() string {
	return "Browser.addPrivacySandboxCoordinatorKeyConfig"
}

// Call sends the request
func (m BrowserAddPrivacySandboxCoordinatorKeyConfig) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// BrowserDownloadWillBegin (experimental) Fired when page is about to start a download.
type BrowserDownloadWillBegin struct {
	// FrameID Id of the frame that caused the download to begin.
	FrameID PageFrameID `json:"frameId"`

	// GUID Global unique identifier of the download.
	GUID string `json:"guid"`

	// URL of the resource being downloaded.
	URL string `json:"url"`

	// SuggestedFilename Suggested file name of the resource (the actual name of the file saved on disk may differ).
	SuggestedFilename string `json:"suggestedFilename"`
}

// ProtoEvent name
func (evt BrowserDownloadWillBegin) ProtoEvent() string {
	return "Browser.downloadWillBegin"
}

// BrowserDownloadProgressState enum
type BrowserDownloadProgressState string

const (
	// BrowserDownloadProgressStateInProgress enum const
	BrowserDownloadProgressStateInProgress BrowserDownloadProgressState = "inProgress"

	// BrowserDownloadProgressStateCompleted enum const
	BrowserDownloadProgressStateCompleted BrowserDownloadProgressState = "completed"

	// BrowserDownloadProgressStateCanceled enum const
	BrowserDownloadProgressStateCanceled BrowserDownloadProgressState = "canceled"
)

// BrowserDownloadProgress (experimental) Fired when download makes progress. Last call has |done| == true.
type BrowserDownloadProgress struct {
	// GUID Global unique identifier of the download.
	GUID string `json:"guid"`

	// TotalBytes Total expected bytes to download.
	TotalBytes float64 `json:"totalBytes"`

	// ReceivedBytes Total bytes received.
	ReceivedBytes float64 `json:"receivedBytes"`

	// State Download status.
	State BrowserDownloadProgressState `json:"state"`

	// FilePath (experimental) (optional) If download is "completed", provides the path of the downloaded file.
	// Depending on the platform, it is not guaranteed to be set, nor the file
	// is guaranteed to exist.
	FilePath string `json:"filePath,omitempty"`
}

// ProtoEvent name
func (evt BrowserDownloadProgress) ProtoEvent() string {
	return "Browser.downloadProgress"
}
