// This file is generated by "./lib/proto/generate"

package proto

import (
	"github.com/ysmood/gson"
)

/*

DigitalCredentials

This domain allows interacting with the Digital Credentials API for automation.

*/

// DigitalCredentialsVirtualWalletAction The type of virtual wallet action.
type DigitalCredentialsVirtualWalletAction string

const (
	// DigitalCredentialsVirtualWalletActionRespond enum const
	DigitalCredentialsVirtualWalletActionRespond DigitalCredentialsVirtualWalletAction = "respond"

	// DigitalCredentialsVirtualWalletActionDecline enum const
	DigitalCredentialsVirtualWalletActionDecline DigitalCredentialsVirtualWalletAction = "decline"

	// DigitalCredentialsVirtualWalletActionWait enum const
	DigitalCredentialsVirtualWalletActionWait DigitalCredentialsVirtualWalletAction = "wait"

	// DigitalCredentialsVirtualWalletActionClear enum const
	DigitalCredentialsVirtualWalletActionClear DigitalCredentialsVirtualWalletAction = "clear"
)

// DigitalCredentialsSetVirtualWalletBehavior Sets the behavior of the virtual wallet for digital credential requests
// issued from this frame.
type DigitalCredentialsSetVirtualWalletBehavior struct {
	// Action The action of the virtual wallet.
	Action DigitalCredentialsVirtualWalletAction `json:"action"`

	// Protocol (optional) The protocol identifier (e.g. "openid4vp"). Required when |action| is
	// "respond", forbidden otherwise.
	Protocol string `json:"protocol,omitempty"`

	// Response (optional) The response data object returned by the wallet.
	// Required when |action| is "respond", forbidden otherwise.
	Response map[string]gson.JSON `json:"response,omitempty"`

	// FrameID (optional) The frame to scope the virtual wallet behavior to.
	FrameID PageFrameID `json:"frameId,omitempty"`
}

// ProtoReq name
func (m DigitalCredentialsSetVirtualWalletBehavior) ProtoReq() string {
	return "DigitalCredentials.setVirtualWalletBehavior"
}

// Call sends the request
func (m DigitalCredentialsSetVirtualWalletBehavior) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}
