// This file is generated by "./lib/proto/generate"

package proto

/*

FileSystem

*/

// FileSystemFile ...
type FileSystemFile struct {
	// Name ...
	Name string `json:"name"`

	// LastModified Timestamp
	LastModified TimeSinceEpoch `json:"lastModified"`

	// Size in bytes
	Size float64 `json:"size"`

	// Type ...
	Type string `json:"type"`
}

// FileSystemDirectory ...
type FileSystemDirectory struct {
	// Name ...
	Name string `json:"name"`

	// NestedDirectories ...
	NestedDirectories []string `json:"nestedDirectories"`

	// NestedFiles Files that are directly nested under this directory.
	NestedFiles []*FileSystemFile `json:"nestedFiles"`
}

// FileSystemBucketFileSystemLocator ...
type FileSystemBucketFileSystemLocator struct {
	// StorageKey Storage key
	StorageKey StorageSerializedStorageKey `json:"storageKey"`

	// BucketName (optional) Bucket name. Not passing a `bucketName` will retrieve the default Bucket. (https://developer.mozilla.org/en-US/docs/Web/API/Storage_API#storage_buckets)
	BucketName string `json:"bucketName,omitempty"`

	// PathComponents Path to the directory using each path component as an array item.
	PathComponents []string `json:"pathComponents"`
}

// FileSystemGetDirectory ...
type FileSystemGetDirectory struct {
	// BucketFileSystemLocator ...
	BucketFileSystemLocator *FileSystemBucketFileSystemLocator `json:"bucketFileSystemLocator"`
}

// ProtoReq name
func (m FileSystemGetDirectory) ProtoReq() string { return "FileSystem.getDirectory" }

// Call the request
func (m FileSystemGetDirectory) Call(c Client) (*FileSystemGetDirectoryResult, error) {
	var res FileSystemGetDirectoryResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// FileSystemGetDirectoryResult ...
type FileSystemGetDirectoryResult struct {
	// Directory Returns the directory object at the path.
	Directory *FileSystemDirectory `json:"directory"`
}
