// This file is generated by "./lib/proto/generate"

package proto

/*

SmartCardEmulation

*/

// SmartCardEmulationResultCode Indicates the PC/SC error code.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__ErrorCodes.html
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/secauthn/authentication-return-values
type SmartCardEmulationResultCode string

const (
	// SmartCardEmulationResultCodeSuccess enum const
	SmartCardEmulationResultCodeSuccess SmartCardEmulationResultCode = "success"

	// SmartCardEmulationResultCodeRemovedCard enum const
	SmartCardEmulationResultCodeRemovedCard SmartCardEmulationResultCode = "removed-card"

	// SmartCardEmulationResultCodeResetCard enum const
	SmartCardEmulationResultCodeResetCard SmartCardEmulationResultCode = "reset-card"

	// SmartCardEmulationResultCodeUnpoweredCard enum const
	SmartCardEmulationResultCodeUnpoweredCard SmartCardEmulationResultCode = "unpowered-card"

	// SmartCardEmulationResultCodeUnresponsiveCard enum const
	SmartCardEmulationResultCodeUnresponsiveCard SmartCardEmulationResultCode = "unresponsive-card"

	// SmartCardEmulationResultCodeUnsupportedCard enum const
	SmartCardEmulationResultCodeUnsupportedCard SmartCardEmulationResultCode = "unsupported-card"

	// SmartCardEmulationResultCodeReaderUnavailable enum const
	SmartCardEmulationResultCodeReaderUnavailable SmartCardEmulationResultCode = "reader-unavailable"

	// SmartCardEmulationResultCodeSharingViolation enum const
	SmartCardEmulationResultCodeSharingViolation SmartCardEmulationResultCode = "sharing-violation"

	// SmartCardEmulationResultCodeNotTransacted enum const
	SmartCardEmulationResultCodeNotTransacted SmartCardEmulationResultCode = "not-transacted"

	// SmartCardEmulationResultCodeNoSmartcard enum const
	SmartCardEmulationResultCodeNoSmartcard SmartCardEmulationResultCode = "no-smartcard"

	// SmartCardEmulationResultCodeProtoMismatch enum const
	SmartCardEmulationResultCodeProtoMismatch SmartCardEmulationResultCode = "proto-mismatch"

	// SmartCardEmulationResultCodeSystemCancelled enum const
	SmartCardEmulationResultCodeSystemCancelled SmartCardEmulationResultCode = "system-cancelled"

	// SmartCardEmulationResultCodeNotReady enum const
	SmartCardEmulationResultCodeNotReady SmartCardEmulationResultCode = "not-ready"

	// SmartCardEmulationResultCodeCancelled enum const
	SmartCardEmulationResultCodeCancelled SmartCardEmulationResultCode = "cancelled"

	// SmartCardEmulationResultCodeInsufficientBuffer enum const
	SmartCardEmulationResultCodeInsufficientBuffer SmartCardEmulationResultCode = "insufficient-buffer"

	// SmartCardEmulationResultCodeInvalidHandle enum const
	SmartCardEmulationResultCodeInvalidHandle SmartCardEmulationResultCode = "invalid-handle"

	// SmartCardEmulationResultCodeInvalidParameter enum const
	SmartCardEmulationResultCodeInvalidParameter SmartCardEmulationResultCode = "invalid-parameter"

	// SmartCardEmulationResultCodeInvalidValue enum const
	SmartCardEmulationResultCodeInvalidValue SmartCardEmulationResultCode = "invalid-value"

	// SmartCardEmulationResultCodeNoMemory enum const
	SmartCardEmulationResultCodeNoMemory SmartCardEmulationResultCode = "no-memory"

	// SmartCardEmulationResultCodeTimeout enum const
	SmartCardEmulationResultCodeTimeout SmartCardEmulationResultCode = "timeout"

	// SmartCardEmulationResultCodeUnknownReader enum const
	SmartCardEmulationResultCodeUnknownReader SmartCardEmulationResultCode = "unknown-reader"

	// SmartCardEmulationResultCodeUnsupportedFeature enum const
	SmartCardEmulationResultCodeUnsupportedFeature SmartCardEmulationResultCode = "unsupported-feature"

	// SmartCardEmulationResultCodeNoReadersAvailable enum const
	SmartCardEmulationResultCodeNoReadersAvailable SmartCardEmulationResultCode = "no-readers-available"

	// SmartCardEmulationResultCodeServiceStopped enum const
	SmartCardEmulationResultCodeServiceStopped SmartCardEmulationResultCode = "service-stopped"

	// SmartCardEmulationResultCodeNoService enum const
	SmartCardEmulationResultCodeNoService SmartCardEmulationResultCode = "no-service"

	// SmartCardEmulationResultCodeCommError enum const
	SmartCardEmulationResultCodeCommError SmartCardEmulationResultCode = "comm-error"

	// SmartCardEmulationResultCodeInternalError enum const
	SmartCardEmulationResultCodeInternalError SmartCardEmulationResultCode = "internal-error"

	// SmartCardEmulationResultCodeServerTooBusy enum const
	SmartCardEmulationResultCodeServerTooBusy SmartCardEmulationResultCode = "server-too-busy"

	// SmartCardEmulationResultCodeUnexpected enum const
	SmartCardEmulationResultCodeUnexpected SmartCardEmulationResultCode = "unexpected"

	// SmartCardEmulationResultCodeShutdown enum const
	SmartCardEmulationResultCodeShutdown SmartCardEmulationResultCode = "shutdown"

	// SmartCardEmulationResultCodeUnknownCard enum const
	SmartCardEmulationResultCodeUnknownCard SmartCardEmulationResultCode = "unknown-card"

	// SmartCardEmulationResultCodeUnknown enum const
	SmartCardEmulationResultCodeUnknown SmartCardEmulationResultCode = "unknown"
)

// SmartCardEmulationShareMode Maps to the |SCARD_SHARE_*| values.
type SmartCardEmulationShareMode string

const (
	// SmartCardEmulationShareModeShared enum const
	SmartCardEmulationShareModeShared SmartCardEmulationShareMode = "shared"

	// SmartCardEmulationShareModeExclusive enum const
	SmartCardEmulationShareModeExclusive SmartCardEmulationShareMode = "exclusive"

	// SmartCardEmulationShareModeDirect enum const
	SmartCardEmulationShareModeDirect SmartCardEmulationShareMode = "direct"
)

// SmartCardEmulationDisposition Indicates what the reader should do with the card.
type SmartCardEmulationDisposition string

const (
	// SmartCardEmulationDispositionLeaveCard enum const
	SmartCardEmulationDispositionLeaveCard SmartCardEmulationDisposition = "leave-card"

	// SmartCardEmulationDispositionResetCard enum const
	SmartCardEmulationDispositionResetCard SmartCardEmulationDisposition = "reset-card"

	// SmartCardEmulationDispositionUnpowerCard enum const
	SmartCardEmulationDispositionUnpowerCard SmartCardEmulationDisposition = "unpower-card"

	// SmartCardEmulationDispositionEjectCard enum const
	SmartCardEmulationDispositionEjectCard SmartCardEmulationDisposition = "eject-card"
)

// SmartCardEmulationConnectionState Maps to |SCARD_*| connection state values.
type SmartCardEmulationConnectionState string

const (
	// SmartCardEmulationConnectionStateAbsent enum const
	SmartCardEmulationConnectionStateAbsent SmartCardEmulationConnectionState = "absent"

	// SmartCardEmulationConnectionStatePresent enum const
	SmartCardEmulationConnectionStatePresent SmartCardEmulationConnectionState = "present"

	// SmartCardEmulationConnectionStateSwallowed enum const
	SmartCardEmulationConnectionStateSwallowed SmartCardEmulationConnectionState = "swallowed"

	// SmartCardEmulationConnectionStatePowered enum const
	SmartCardEmulationConnectionStatePowered SmartCardEmulationConnectionState = "powered"

	// SmartCardEmulationConnectionStateNegotiable enum const
	SmartCardEmulationConnectionStateNegotiable SmartCardEmulationConnectionState = "negotiable"

	// SmartCardEmulationConnectionStateSpecific enum const
	SmartCardEmulationConnectionStateSpecific SmartCardEmulationConnectionState = "specific"
)

// SmartCardEmulationReaderStateFlags Maps to the |SCARD_STATE_*| flags.
type SmartCardEmulationReaderStateFlags struct {
	// Unaware (optional) ...
	Unaware bool `json:"unaware,omitempty"`

	// Ignore (optional) ...
	Ignore bool `json:"ignore,omitempty"`

	// Changed (optional) ...
	Changed bool `json:"changed,omitempty"`

	// Unknown (optional) ...
	Unknown bool `json:"unknown,omitempty"`

	// Unavailable (optional) ...
	Unavailable bool `json:"unavailable,omitempty"`

	// Empty (optional) ...
	Empty bool `json:"empty,omitempty"`

	// Present (optional) ...
	Present bool `json:"present,omitempty"`

	// Exclusive (optional) ...
	Exclusive bool `json:"exclusive,omitempty"`

	// Inuse (optional) ...
	Inuse bool `json:"inuse,omitempty"`

	// Mute (optional) ...
	Mute bool `json:"mute,omitempty"`

	// Unpowered (optional) ...
	Unpowered bool `json:"unpowered,omitempty"`
}

// SmartCardEmulationProtocolSet Maps to the |SCARD_PROTOCOL_*| flags.
type SmartCardEmulationProtocolSet struct {
	// T0 (optional) ...
	T0 bool `json:"t0,omitempty"`

	// T1 (optional) ...
	T1 bool `json:"t1,omitempty"`

	// Raw (optional) ...
	Raw bool `json:"raw,omitempty"`
}

// SmartCardEmulationProtocol Maps to the |SCARD_PROTOCOL_*| values.
type SmartCardEmulationProtocol string

const (
	// SmartCardEmulationProtocolT0 enum const
	SmartCardEmulationProtocolT0 SmartCardEmulationProtocol = "t0"

	// SmartCardEmulationProtocolT1 enum const
	SmartCardEmulationProtocolT1 SmartCardEmulationProtocol = "t1"

	// SmartCardEmulationProtocolRaw enum const
	SmartCardEmulationProtocolRaw SmartCardEmulationProtocol = "raw"
)

// SmartCardEmulationReaderStateIn ...
type SmartCardEmulationReaderStateIn struct {
	// Reader ...
	Reader string `json:"reader"`

	// CurrentState ...
	CurrentState *SmartCardEmulationReaderStateFlags `json:"currentState"`

	// CurrentInsertionCount ...
	CurrentInsertionCount int `json:"currentInsertionCount"`
}

// SmartCardEmulationReaderStateOut ...
type SmartCardEmulationReaderStateOut struct {
	// Reader ...
	Reader string `json:"reader"`

	// EventState ...
	EventState *SmartCardEmulationReaderStateFlags `json:"eventState"`

	// EventCount ...
	EventCount int `json:"eventCount"`

	// Atr ...
	Atr []byte `json:"atr"`
}

// SmartCardEmulationEnable Enables the |SmartCardEmulation| domain.
type SmartCardEmulationEnable struct{}

// ProtoReq name
func (m SmartCardEmulationEnable) ProtoReq() string { return "SmartCardEmulation.enable" }

// Call sends the request
func (m SmartCardEmulationEnable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationDisable Disables the |SmartCardEmulation| domain.
type SmartCardEmulationDisable struct{}

// ProtoReq name
func (m SmartCardEmulationDisable) ProtoReq() string { return "SmartCardEmulation.disable" }

// Call sends the request
func (m SmartCardEmulationDisable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportEstablishContextResult Reports the successful result of a |SCardEstablishContext| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext
type SmartCardEmulationReportEstablishContextResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ContextID ...
	ContextID int `json:"contextId"`
}

// ProtoReq name
func (m SmartCardEmulationReportEstablishContextResult) ProtoReq() string {
	return "SmartCardEmulation.reportEstablishContextResult"
}

// Call sends the request
func (m SmartCardEmulationReportEstablishContextResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportReleaseContextResult Reports the successful result of a |SCardReleaseContext| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext
type SmartCardEmulationReportReleaseContextResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`
}

// ProtoReq name
func (m SmartCardEmulationReportReleaseContextResult) ProtoReq() string {
	return "SmartCardEmulation.reportReleaseContextResult"
}

// Call sends the request
func (m SmartCardEmulationReportReleaseContextResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportListReadersResult Reports the successful result of a |SCardListReaders| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa
type SmartCardEmulationReportListReadersResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Readers ...
	Readers []string `json:"readers"`
}

// ProtoReq name
func (m SmartCardEmulationReportListReadersResult) ProtoReq() string {
	return "SmartCardEmulation.reportListReadersResult"
}

// Call sends the request
func (m SmartCardEmulationReportListReadersResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportGetStatusChangeResult Reports the successful result of a |SCardGetStatusChange| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea
type SmartCardEmulationReportGetStatusChangeResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ReaderStates ...
	ReaderStates []*SmartCardEmulationReaderStateOut `json:"readerStates"`
}

// ProtoReq name
func (m SmartCardEmulationReportGetStatusChangeResult) ProtoReq() string {
	return "SmartCardEmulation.reportGetStatusChangeResult"
}

// Call sends the request
func (m SmartCardEmulationReportGetStatusChangeResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportBeginTransactionResult Reports the result of a |SCardBeginTransaction| call.
// On success, this creates a new transaction object.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction
type SmartCardEmulationReportBeginTransactionResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`
}

// ProtoReq name
func (m SmartCardEmulationReportBeginTransactionResult) ProtoReq() string {
	return "SmartCardEmulation.reportBeginTransactionResult"
}

// Call sends the request
func (m SmartCardEmulationReportBeginTransactionResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportPlainResult Reports the successful result of a call that returns only a result code.
// Used for: |SCardCancel|, |SCardDisconnect|, |SCardSetAttrib|, |SCardEndTransaction|.
//
// This maps to:
//
//  1. SCardCancel
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel
//
//  2. SCardDisconnect
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect
//
//  3. SCardSetAttrib
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib
//
//  4. SCardEndTransaction
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction
type SmartCardEmulationReportPlainResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`
}

// ProtoReq name
func (m SmartCardEmulationReportPlainResult) ProtoReq() string {
	return "SmartCardEmulation.reportPlainResult"
}

// Call sends the request
func (m SmartCardEmulationReportPlainResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportConnectResult Reports the successful result of a |SCardConnect| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta
type SmartCardEmulationReportConnectResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`

	// ActiveProtocol (optional) ...
	ActiveProtocol SmartCardEmulationProtocol `json:"activeProtocol,omitempty"`
}

// ProtoReq name
func (m SmartCardEmulationReportConnectResult) ProtoReq() string {
	return "SmartCardEmulation.reportConnectResult"
}

// Call sends the request
func (m SmartCardEmulationReportConnectResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportDataResult Reports the successful result of a call that sends back data on success.
// Used for |SCardTransmit|, |SCardControl|, and |SCardGetAttrib|.
//
// This maps to:
//
//  1. SCardTransmit
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit
//
//  2. SCardControl
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol
//
//  3. SCardGetAttrib
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib
type SmartCardEmulationReportDataResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Data ...
	Data []byte `json:"data"`
}

// ProtoReq name
func (m SmartCardEmulationReportDataResult) ProtoReq() string {
	return "SmartCardEmulation.reportDataResult"
}

// Call sends the request
func (m SmartCardEmulationReportDataResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportStatusResult Reports the successful result of a |SCardStatus| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa
type SmartCardEmulationReportStatusResult struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ReaderName ...
	ReaderName string `json:"readerName"`

	// State ...
	State SmartCardEmulationConnectionState `json:"state"`

	// Atr ...
	Atr []byte `json:"atr"`

	// Protocol (optional) ...
	Protocol SmartCardEmulationProtocol `json:"protocol,omitempty"`
}

// ProtoReq name
func (m SmartCardEmulationReportStatusResult) ProtoReq() string {
	return "SmartCardEmulation.reportStatusResult"
}

// Call sends the request
func (m SmartCardEmulationReportStatusResult) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationReportError Reports an error result for the given request.
type SmartCardEmulationReportError struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ResultCode ...
	ResultCode SmartCardEmulationResultCode `json:"resultCode"`
}

// ProtoReq name
func (m SmartCardEmulationReportError) ProtoReq() string { return "SmartCardEmulation.reportError" }

// Call sends the request
func (m SmartCardEmulationReportError) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// SmartCardEmulationEstablishContextRequested Fired when |SCardEstablishContext| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext
type SmartCardEmulationEstablishContextRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`
}

// ProtoEvent name
func (evt SmartCardEmulationEstablishContextRequested) ProtoEvent() string {
	return "SmartCardEmulation.establishContextRequested"
}

// SmartCardEmulationReleaseContextRequested Fired when |SCardReleaseContext| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext
type SmartCardEmulationReleaseContextRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ContextID ...
	ContextID int `json:"contextId"`
}

// ProtoEvent name
func (evt SmartCardEmulationReleaseContextRequested) ProtoEvent() string {
	return "SmartCardEmulation.releaseContextRequested"
}

// SmartCardEmulationListReadersRequested Fired when |SCardListReaders| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa
type SmartCardEmulationListReadersRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ContextID ...
	ContextID int `json:"contextId"`
}

// ProtoEvent name
func (evt SmartCardEmulationListReadersRequested) ProtoEvent() string {
	return "SmartCardEmulation.listReadersRequested"
}

// SmartCardEmulationGetStatusChangeRequested Fired when |SCardGetStatusChange| is called. Timeout is specified in milliseconds.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea
type SmartCardEmulationGetStatusChangeRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ContextID ...
	ContextID int `json:"contextId"`

	// ReaderStates ...
	ReaderStates []*SmartCardEmulationReaderStateIn `json:"readerStates"`

	// Timeout (optional) in milliseconds, if absent, it means "infinite"
	Timeout *int `json:"timeout,omitempty"`
}

// ProtoEvent name
func (evt SmartCardEmulationGetStatusChangeRequested) ProtoEvent() string {
	return "SmartCardEmulation.getStatusChangeRequested"
}

// SmartCardEmulationCancelRequested Fired when |SCardCancel| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel
type SmartCardEmulationCancelRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ContextID ...
	ContextID int `json:"contextId"`
}

// ProtoEvent name
func (evt SmartCardEmulationCancelRequested) ProtoEvent() string {
	return "SmartCardEmulation.cancelRequested"
}

// SmartCardEmulationConnectRequested Fired when |SCardConnect| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta
type SmartCardEmulationConnectRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// ContextID ...
	ContextID int `json:"contextId"`

	// Reader ...
	Reader string `json:"reader"`

	// ShareMode ...
	ShareMode SmartCardEmulationShareMode `json:"shareMode"`

	// PreferredProtocols ...
	PreferredProtocols *SmartCardEmulationProtocolSet `json:"preferredProtocols"`
}

// ProtoEvent name
func (evt SmartCardEmulationConnectRequested) ProtoEvent() string {
	return "SmartCardEmulation.connectRequested"
}

// SmartCardEmulationDisconnectRequested Fired when |SCardDisconnect| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect
type SmartCardEmulationDisconnectRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`

	// Disposition ...
	Disposition SmartCardEmulationDisposition `json:"disposition"`
}

// ProtoEvent name
func (evt SmartCardEmulationDisconnectRequested) ProtoEvent() string {
	return "SmartCardEmulation.disconnectRequested"
}

// SmartCardEmulationTransmitRequested Fired when |SCardTransmit| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit
type SmartCardEmulationTransmitRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`

	// Data ...
	Data []byte `json:"data"`

	// Protocol (optional) ...
	Protocol SmartCardEmulationProtocol `json:"protocol,omitempty"`
}

// ProtoEvent name
func (evt SmartCardEmulationTransmitRequested) ProtoEvent() string {
	return "SmartCardEmulation.transmitRequested"
}

// SmartCardEmulationControlRequested Fired when |SCardControl| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol
type SmartCardEmulationControlRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`

	// ControlCode ...
	ControlCode int `json:"controlCode"`

	// Data ...
	Data []byte `json:"data"`
}

// ProtoEvent name
func (evt SmartCardEmulationControlRequested) ProtoEvent() string {
	return "SmartCardEmulation.controlRequested"
}

// SmartCardEmulationGetAttribRequested Fired when |SCardGetAttrib| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib
type SmartCardEmulationGetAttribRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`

	// AttribID ...
	AttribID int `json:"attribId"`
}

// ProtoEvent name
func (evt SmartCardEmulationGetAttribRequested) ProtoEvent() string {
	return "SmartCardEmulation.getAttribRequested"
}

// SmartCardEmulationSetAttribRequested Fired when |SCardSetAttrib| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib
type SmartCardEmulationSetAttribRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`

	// AttribID ...
	AttribID int `json:"attribId"`

	// Data ...
	Data []byte `json:"data"`
}

// ProtoEvent name
func (evt SmartCardEmulationSetAttribRequested) ProtoEvent() string {
	return "SmartCardEmulation.setAttribRequested"
}

// SmartCardEmulationStatusRequested Fired when |SCardStatus| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa
type SmartCardEmulationStatusRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`
}

// ProtoEvent name
func (evt SmartCardEmulationStatusRequested) ProtoEvent() string {
	return "SmartCardEmulation.statusRequested"
}

// SmartCardEmulationBeginTransactionRequested Fired when |SCardBeginTransaction| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction
type SmartCardEmulationBeginTransactionRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`
}

// ProtoEvent name
func (evt SmartCardEmulationBeginTransactionRequested) ProtoEvent() string {
	return "SmartCardEmulation.beginTransactionRequested"
}

// SmartCardEmulationEndTransactionRequested Fired when |SCardEndTransaction| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction
type SmartCardEmulationEndTransactionRequested struct {
	// RequestID ...
	RequestID string `json:"requestId"`

	// Handle ...
	Handle int `json:"handle"`

	// Disposition ...
	Disposition SmartCardEmulationDisposition `json:"disposition"`
}

// ProtoEvent name
func (evt SmartCardEmulationEndTransactionRequested) ProtoEvent() string {
	return "SmartCardEmulation.endTransactionRequested"
}
