// This file is generated by "./lib/proto/generate"

package proto

import (
	"github.com/ysmood/gson"
)

/*

Storage

*/

// StorageSerializedStorageKey ...
type StorageSerializedStorageKey string

// StorageStorageType Enum of possible storage types.
type StorageStorageType string

const (
	// StorageStorageTypeCookies enum const
	StorageStorageTypeCookies StorageStorageType = "cookies"

	// StorageStorageTypeFileSystems enum const
	StorageStorageTypeFileSystems StorageStorageType = "file_systems"

	// StorageStorageTypeIndexeddb enum const
	StorageStorageTypeIndexeddb StorageStorageType = "indexeddb"

	// StorageStorageTypeLocalStorage enum const
	StorageStorageTypeLocalStorage StorageStorageType = "local_storage"

	// StorageStorageTypeShaderCache enum const
	StorageStorageTypeShaderCache StorageStorageType = "shader_cache"

	// StorageStorageTypeWebsql enum const
	StorageStorageTypeWebsql StorageStorageType = "websql"

	// StorageStorageTypeServiceWorkers enum const
	StorageStorageTypeServiceWorkers StorageStorageType = "service_workers"

	// StorageStorageTypeCacheStorage enum const
	StorageStorageTypeCacheStorage StorageStorageType = "cache_storage"

	// StorageStorageTypeInterestGroups enum const
	StorageStorageTypeInterestGroups StorageStorageType = "interest_groups"

	// StorageStorageTypeSharedStorage enum const
	StorageStorageTypeSharedStorage StorageStorageType = "shared_storage"

	// StorageStorageTypeStorageBuckets enum const
	StorageStorageTypeStorageBuckets StorageStorageType = "storage_buckets"

	// StorageStorageTypeAll enum const
	StorageStorageTypeAll StorageStorageType = "all"

	// StorageStorageTypeOther enum const
	StorageStorageTypeOther StorageStorageType = "other"
)

// StorageUsageForType Usage for a storage type.
type StorageUsageForType struct {
	// StorageType Name of storage type.
	StorageType StorageStorageType `json:"storageType"`

	// Usage Storage usage (bytes).
	Usage float64 `json:"usage"`
}

// StorageTrustTokens (experimental) Pair of issuer origin and number of available (signed, but not used) Trust
// Tokens from that issuer.
type StorageTrustTokens struct {
	// IssuerOrigin ...
	IssuerOrigin string `json:"issuerOrigin"`

	// Count ...
	Count float64 `json:"count"`
}

// StorageInterestGroupAuctionID Protected audience interest group auction identifier.
type StorageInterestGroupAuctionID string

// StorageInterestGroupAccessType Enum of interest group access types.
type StorageInterestGroupAccessType string

const (
	// StorageInterestGroupAccessTypeJoin enum const
	StorageInterestGroupAccessTypeJoin StorageInterestGroupAccessType = "join"

	// StorageInterestGroupAccessTypeLeave enum const
	StorageInterestGroupAccessTypeLeave StorageInterestGroupAccessType = "leave"

	// StorageInterestGroupAccessTypeUpdate enum const
	StorageInterestGroupAccessTypeUpdate StorageInterestGroupAccessType = "update"

	// StorageInterestGroupAccessTypeLoaded enum const
	StorageInterestGroupAccessTypeLoaded StorageInterestGroupAccessType = "loaded"

	// StorageInterestGroupAccessTypeBid enum const
	StorageInterestGroupAccessTypeBid StorageInterestGroupAccessType = "bid"

	// StorageInterestGroupAccessTypeWin enum const
	StorageInterestGroupAccessTypeWin StorageInterestGroupAccessType = "win"

	// StorageInterestGroupAccessTypeAdditionalBid enum const
	StorageInterestGroupAccessTypeAdditionalBid StorageInterestGroupAccessType = "additionalBid"

	// StorageInterestGroupAccessTypeAdditionalBidWin enum const
	StorageInterestGroupAccessTypeAdditionalBidWin StorageInterestGroupAccessType = "additionalBidWin"

	// StorageInterestGroupAccessTypeTopLevelBid enum const
	StorageInterestGroupAccessTypeTopLevelBid StorageInterestGroupAccessType = "topLevelBid"

	// StorageInterestGroupAccessTypeTopLevelAdditionalBid enum const
	StorageInterestGroupAccessTypeTopLevelAdditionalBid StorageInterestGroupAccessType = "topLevelAdditionalBid"

	// StorageInterestGroupAccessTypeClear enum const
	StorageInterestGroupAccessTypeClear StorageInterestGroupAccessType = "clear"
)

// StorageInterestGroupAuctionEventType Enum of auction events.
type StorageInterestGroupAuctionEventType string

const (
	// StorageInterestGroupAuctionEventTypeStarted enum const
	StorageInterestGroupAuctionEventTypeStarted StorageInterestGroupAuctionEventType = "started"

	// StorageInterestGroupAuctionEventTypeConfigResolved enum const
	StorageInterestGroupAuctionEventTypeConfigResolved StorageInterestGroupAuctionEventType = "configResolved"
)

// StorageInterestGroupAuctionFetchType Enum of network fetches auctions can do.
type StorageInterestGroupAuctionFetchType string

const (
	// StorageInterestGroupAuctionFetchTypeBidderJs enum const
	StorageInterestGroupAuctionFetchTypeBidderJs StorageInterestGroupAuctionFetchType = "bidderJs"

	// StorageInterestGroupAuctionFetchTypeBidderWasm enum const
	StorageInterestGroupAuctionFetchTypeBidderWasm StorageInterestGroupAuctionFetchType = "bidderWasm"

	// StorageInterestGroupAuctionFetchTypeSellerJs enum const
	StorageInterestGroupAuctionFetchTypeSellerJs StorageInterestGroupAuctionFetchType = "sellerJs"

	// StorageInterestGroupAuctionFetchTypeBidderTrustedSignals enum const
	StorageInterestGroupAuctionFetchTypeBidderTrustedSignals StorageInterestGroupAuctionFetchType = "bidderTrustedSignals"

	// StorageInterestGroupAuctionFetchTypeSellerTrustedSignals enum const
	StorageInterestGroupAuctionFetchTypeSellerTrustedSignals StorageInterestGroupAuctionFetchType = "sellerTrustedSignals"
)

// StorageSharedStorageAccessScope Enum of shared storage access scopes.
type StorageSharedStorageAccessScope string

const (
	// StorageSharedStorageAccessScopeWindow enum const
	StorageSharedStorageAccessScopeWindow StorageSharedStorageAccessScope = "window"

	// StorageSharedStorageAccessScopeSharedStorageWorklet enum const
	StorageSharedStorageAccessScopeSharedStorageWorklet StorageSharedStorageAccessScope = "sharedStorageWorklet"

	// StorageSharedStorageAccessScopeProtectedAudienceWorklet enum const
	StorageSharedStorageAccessScopeProtectedAudienceWorklet StorageSharedStorageAccessScope = "protectedAudienceWorklet"

	// StorageSharedStorageAccessScopeHeader enum const
	StorageSharedStorageAccessScopeHeader StorageSharedStorageAccessScope = "header"
)

// StorageSharedStorageAccessMethod Enum of shared storage access methods.
type StorageSharedStorageAccessMethod string

const (
	// StorageSharedStorageAccessMethodAddModule enum const
	StorageSharedStorageAccessMethodAddModule StorageSharedStorageAccessMethod = "addModule"

	// StorageSharedStorageAccessMethodCreateWorklet enum const
	StorageSharedStorageAccessMethodCreateWorklet StorageSharedStorageAccessMethod = "createWorklet"

	// StorageSharedStorageAccessMethodSelectURL enum const
	StorageSharedStorageAccessMethodSelectURL StorageSharedStorageAccessMethod = "selectURL"

	// StorageSharedStorageAccessMethodRun enum const
	StorageSharedStorageAccessMethodRun StorageSharedStorageAccessMethod = "run"

	// StorageSharedStorageAccessMethodBatchUpdate enum const
	StorageSharedStorageAccessMethodBatchUpdate StorageSharedStorageAccessMethod = "batchUpdate"

	// StorageSharedStorageAccessMethodSet enum const
	StorageSharedStorageAccessMethodSet StorageSharedStorageAccessMethod = "set"

	// StorageSharedStorageAccessMethodAppend enum const
	StorageSharedStorageAccessMethodAppend StorageSharedStorageAccessMethod = "append"

	// StorageSharedStorageAccessMethodDelete enum const
	StorageSharedStorageAccessMethodDelete StorageSharedStorageAccessMethod = "delete"

	// StorageSharedStorageAccessMethodClear enum const
	StorageSharedStorageAccessMethodClear StorageSharedStorageAccessMethod = "clear"

	// StorageSharedStorageAccessMethodGet enum const
	StorageSharedStorageAccessMethodGet StorageSharedStorageAccessMethod = "get"

	// StorageSharedStorageAccessMethodKeys enum const
	StorageSharedStorageAccessMethodKeys StorageSharedStorageAccessMethod = "keys"

	// StorageSharedStorageAccessMethodValues enum const
	StorageSharedStorageAccessMethodValues StorageSharedStorageAccessMethod = "values"

	// StorageSharedStorageAccessMethodEntries enum const
	StorageSharedStorageAccessMethodEntries StorageSharedStorageAccessMethod = "entries"

	// StorageSharedStorageAccessMethodLength enum const
	StorageSharedStorageAccessMethodLength StorageSharedStorageAccessMethod = "length"

	// StorageSharedStorageAccessMethodRemainingBudget enum const
	StorageSharedStorageAccessMethodRemainingBudget StorageSharedStorageAccessMethod = "remainingBudget"
)

// StorageSharedStorageEntry Struct for a single key-value pair in an origin's shared storage.
type StorageSharedStorageEntry struct {
	// Key ...
	Key string `json:"key"`

	// Value ...
	Value string `json:"value"`
}

// StorageSharedStorageMetadata Details for an origin's shared storage.
type StorageSharedStorageMetadata struct {
	// CreationTime Time when the origin's shared storage was last created.
	CreationTime TimeSinceEpoch `json:"creationTime"`

	// Length Number of key-value pairs stored in origin's shared storage.
	Length int `json:"length"`

	// RemainingBudget Current amount of bits of entropy remaining in the navigation budget.
	RemainingBudget float64 `json:"remainingBudget"`

	// BytesUsed Total number of bytes stored as key-value pairs in origin's shared
	// storage.
	BytesUsed int `json:"bytesUsed"`
}

// StorageSharedStoragePrivateAggregationConfig Represents a dictionary object passed in as privateAggregationConfig to
// run or selectURL.
type StorageSharedStoragePrivateAggregationConfig struct {
	// AggregationCoordinatorOrigin (optional) The chosen aggregation service deployment.
	AggregationCoordinatorOrigin string `json:"aggregationCoordinatorOrigin,omitempty"`

	// ContextID (optional) The context ID provided.
	ContextID string `json:"contextId,omitempty"`

	// FilteringIDMaxBytes Configures the maximum size allowed for filtering IDs.
	FilteringIDMaxBytes int `json:"filteringIdMaxBytes"`

	// MaxContributions (optional) The limit on the number of contributions in the final report.
	MaxContributions *int `json:"maxContributions,omitempty"`
}

// StorageSharedStorageReportingMetadata Pair of reporting metadata details for a candidate URL for `selectURL()`.
type StorageSharedStorageReportingMetadata struct {
	// EventType ...
	EventType string `json:"eventType"`

	// ReportingURL ...
	ReportingURL string `json:"reportingUrl"`
}

// StorageSharedStorageURLWithMetadata Bundles a candidate URL with its reporting metadata.
type StorageSharedStorageURLWithMetadata struct {
	// URL Spec of candidate URL.
	URL string `json:"url"`

	// ReportingMetadata Any associated reporting metadata.
	ReportingMetadata []*StorageSharedStorageReportingMetadata `json:"reportingMetadata"`
}

// StorageSharedStorageAccessParams Bundles the parameters for shared storage access events whose
// presence/absence can vary according to SharedStorageAccessType.
type StorageSharedStorageAccessParams struct {
	// ScriptSourceURL (optional) Spec of the module script URL.
	// Present only for SharedStorageAccessMethods: addModule and
	// createWorklet.
	ScriptSourceURL string `json:"scriptSourceUrl,omitempty"`

	// DataOrigin (optional) String denoting "context-origin", "script-origin", or a custom
	// origin to be used as the worklet's data origin.
	// Present only for SharedStorageAccessMethod: createWorklet.
	DataOrigin string `json:"dataOrigin,omitempty"`

	// OperationName (optional) Name of the registered operation to be run.
	// Present only for SharedStorageAccessMethods: run and selectURL.
	OperationName string `json:"operationName,omitempty"`

	// OperationID (optional) ID of the operation call.
	// Present only for SharedStorageAccessMethods: run and selectURL.
	OperationID string `json:"operationId,omitempty"`

	// KeepAlive (optional) Whether or not to keep the worket alive for future run or selectURL
	// calls.
	// Present only for SharedStorageAccessMethods: run and selectURL.
	KeepAlive bool `json:"keepAlive,omitempty"`

	// PrivateAggregationConfig (optional) Configures the private aggregation options.
	// Present only for SharedStorageAccessMethods: run and selectURL.
	PrivateAggregationConfig *StorageSharedStoragePrivateAggregationConfig `json:"privateAggregationConfig,omitempty"`

	// SerializedData (optional) The operation's serialized data in bytes (converted to a string).
	// Present only for SharedStorageAccessMethods: run and selectURL.
	// TODO(crbug.com/401011862): Consider updating this parameter to binary.
	SerializedData string `json:"serializedData,omitempty"`

	// UrlsWithMetadata (optional) Array of candidate URLs' specs, along with any associated metadata.
	// Present only for SharedStorageAccessMethod: selectURL.
	UrlsWithMetadata []*StorageSharedStorageURLWithMetadata `json:"urlsWithMetadata,omitempty"`

	// UrnUUID (optional) Spec of the URN:UUID generated for a selectURL call.
	// Present only for SharedStorageAccessMethod: selectURL.
	UrnUUID string `json:"urnUuid,omitempty"`

	// Key (optional) Key for a specific entry in an origin's shared storage.
	// Present only for SharedStorageAccessMethods: set, append, delete, and
	// get.
	Key string `json:"key,omitempty"`

	// Value (optional) Value for a specific entry in an origin's shared storage.
	// Present only for SharedStorageAccessMethods: set and append.
	Value string `json:"value,omitempty"`

	// IgnoreIfPresent (optional) Whether or not to set an entry for a key if that key is already present.
	// Present only for SharedStorageAccessMethod: set.
	IgnoreIfPresent bool `json:"ignoreIfPresent,omitempty"`

	// WorkletOrdinal (optional) A number denoting the (0-based) order of the worklet's
	// creation relative to all other shared storage worklets created by
	// documents using the current storage partition.
	// Present only for SharedStorageAccessMethods: addModule, createWorklet.
	WorkletOrdinal *int `json:"workletOrdinal,omitempty"`

	// WorkletTargetID (optional) Hex representation of the DevTools token used as the TargetID for the
	// associated shared storage worklet.
	// Present only for SharedStorageAccessMethods: addModule, createWorklet,
	// run, selectURL, and any other SharedStorageAccessMethod when the
	// SharedStorageAccessScope is sharedStorageWorklet.
	WorkletTargetID TargetTargetID `json:"workletTargetId,omitempty"`

	// WithLock (optional) Name of the lock to be acquired, if present.
	// Optionally present only for SharedStorageAccessMethods: batchUpdate,
	// set, append, delete, and clear.
	WithLock string `json:"withLock,omitempty"`

	// BatchUpdateID (optional) If the method has been called as part of a batchUpdate, then this
	// number identifies the batch to which it belongs.
	// Optionally present only for SharedStorageAccessMethods:
	// batchUpdate (required), set, append, delete, and clear.
	BatchUpdateID string `json:"batchUpdateId,omitempty"`

	// BatchSize (optional) Number of modifier methods sent in batch.
	// Present only for SharedStorageAccessMethod: batchUpdate.
	BatchSize *int `json:"batchSize,omitempty"`
}

// StorageStorageBucketsDurability ...
type StorageStorageBucketsDurability string

const (
	// StorageStorageBucketsDurabilityRelaxed enum const
	StorageStorageBucketsDurabilityRelaxed StorageStorageBucketsDurability = "relaxed"

	// StorageStorageBucketsDurabilityStrict enum const
	StorageStorageBucketsDurabilityStrict StorageStorageBucketsDurability = "strict"
)

// StorageStorageBucket ...
type StorageStorageBucket struct {
	// StorageKey ...
	StorageKey StorageSerializedStorageKey `json:"storageKey"`

	// Name (optional) If not specified, it is the default bucket of the storageKey.
	Name string `json:"name,omitempty"`
}

// StorageStorageBucketInfo ...
type StorageStorageBucketInfo struct {
	// Bucket ...
	Bucket *StorageStorageBucket `json:"bucket"`

	// ID ...
	ID string `json:"id"`

	// Expiration ...
	Expiration TimeSinceEpoch `json:"expiration"`

	// Quota Storage quota (bytes).
	Quota float64 `json:"quota"`

	// Persistent ...
	Persistent bool `json:"persistent"`

	// Durability ...
	Durability StorageStorageBucketsDurability `json:"durability"`
}

// StorageRelatedWebsiteSet (experimental) A single Related Website Set object.
type StorageRelatedWebsiteSet struct {
	// PrimarySites The primary site of this set, along with the ccTLDs if there is any.
	PrimarySites []string `json:"primarySites"`

	// AssociatedSites The associated sites of this set, along with the ccTLDs if there is any.
	AssociatedSites []string `json:"associatedSites"`

	// ServiceSites The service sites of this set, along with the ccTLDs if there is any.
	ServiceSites []string `json:"serviceSites"`
}

// StorageGetStorageKeyForFrame (deprecated) Returns a storage key given a frame id.
// Deprecated. Please use Storage.getStorageKey instead.
type StorageGetStorageKeyForFrame struct {
	// FrameID ...
	FrameID PageFrameID `json:"frameId"`
}

// ProtoReq name
func (m StorageGetStorageKeyForFrame) ProtoReq() string { return "Storage.getStorageKeyForFrame" }

// Call the request
func (m StorageGetStorageKeyForFrame) Call(c Client) (*StorageGetStorageKeyForFrameResult, error) {
	var res StorageGetStorageKeyForFrameResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetStorageKeyForFrameResult (deprecated) ...
type StorageGetStorageKeyForFrameResult struct {
	// StorageKey ...
	StorageKey StorageSerializedStorageKey `json:"storageKey"`
}

// StorageGetStorageKey (experimental) Returns storage key for the given frame. If no frame ID is provided,
// the storage key of the target executing this command is returned.
type StorageGetStorageKey struct {
	// FrameID (optional) ...
	FrameID PageFrameID `json:"frameId,omitempty"`
}

// ProtoReq name
func (m StorageGetStorageKey) ProtoReq() string { return "Storage.getStorageKey" }

// Call the request
func (m StorageGetStorageKey) Call(c Client) (*StorageGetStorageKeyResult, error) {
	var res StorageGetStorageKeyResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetStorageKeyResult (experimental) ...
type StorageGetStorageKeyResult struct {
	// StorageKey ...
	StorageKey StorageSerializedStorageKey `json:"storageKey"`
}

// StorageClearDataForOrigin Clears storage for origin.
type StorageClearDataForOrigin struct {
	// Origin Security origin.
	Origin string `json:"origin"`

	// StorageTypes Comma separated list of StorageType to clear.
	StorageTypes string `json:"storageTypes"`
}

// ProtoReq name
func (m StorageClearDataForOrigin) ProtoReq() string { return "Storage.clearDataForOrigin" }

// Call sends the request
func (m StorageClearDataForOrigin) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageClearDataForStorageKey Clears storage for storage key.
type StorageClearDataForStorageKey struct {
	// StorageKey Storage key.
	StorageKey string `json:"storageKey"`

	// StorageTypes Comma separated list of StorageType to clear.
	StorageTypes string `json:"storageTypes"`
}

// ProtoReq name
func (m StorageClearDataForStorageKey) ProtoReq() string { return "Storage.clearDataForStorageKey" }

// Call sends the request
func (m StorageClearDataForStorageKey) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageGetCookies Returns all browser cookies.
type StorageGetCookies struct {
	// BrowserContextID (optional) Browser context to use when called on the browser endpoint.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m StorageGetCookies) ProtoReq() string { return "Storage.getCookies" }

// Call the request
func (m StorageGetCookies) Call(c Client) (*StorageGetCookiesResult, error) {
	var res StorageGetCookiesResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetCookiesResult ...
type StorageGetCookiesResult struct {
	// Cookies Array of cookie objects.
	Cookies []*NetworkCookie `json:"cookies"`
}

// StorageSetCookies Sets given cookies.
type StorageSetCookies struct {
	// Cookies to be set.
	Cookies []*NetworkCookieParam `json:"cookies"`

	// BrowserContextID (optional) Browser context to use when called on the browser endpoint.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m StorageSetCookies) ProtoReq() string { return "Storage.setCookies" }

// Call sends the request
func (m StorageSetCookies) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageClearCookies Clears cookies.
type StorageClearCookies struct {
	// BrowserContextID (optional) Browser context to use when called on the browser endpoint.
	BrowserContextID BrowserBrowserContextID `json:"browserContextId,omitempty"`
}

// ProtoReq name
func (m StorageClearCookies) ProtoReq() string { return "Storage.clearCookies" }

// Call sends the request
func (m StorageClearCookies) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageGetUsageAndQuota Returns usage and quota in bytes.
type StorageGetUsageAndQuota struct {
	// Origin Security origin.
	Origin string `json:"origin"`
}

// ProtoReq name
func (m StorageGetUsageAndQuota) ProtoReq() string { return "Storage.getUsageAndQuota" }

// Call the request
func (m StorageGetUsageAndQuota) Call(c Client) (*StorageGetUsageAndQuotaResult, error) {
	var res StorageGetUsageAndQuotaResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetUsageAndQuotaResult ...
type StorageGetUsageAndQuotaResult struct {
	// Usage Storage usage (bytes).
	Usage float64 `json:"usage"`

	// Quota Storage quota (bytes).
	Quota float64 `json:"quota"`

	// OverrideActive Whether or not the origin has an active storage quota override
	OverrideActive bool `json:"overrideActive"`

	// UsageBreakdown Storage usage per type (bytes).
	UsageBreakdown []*StorageUsageForType `json:"usageBreakdown"`
}

// StorageOverrideQuotaForOrigin (experimental) Override quota for the specified origin
type StorageOverrideQuotaForOrigin struct {
	// Origin Security origin.
	Origin string `json:"origin"`

	// QuotaSize (optional) The quota size (in bytes) to override the original quota with.
	// If this is called multiple times, the overridden quota will be equal to
	// the quotaSize provided in the final call. If this is called without
	// specifying a quotaSize, the quota will be reset to the default value for
	// the specified origin. If this is called multiple times with different
	// origins, the override will be maintained for each origin until it is
	// disabled (called without a quotaSize).
	QuotaSize *float64 `json:"quotaSize,omitempty"`
}

// ProtoReq name
func (m StorageOverrideQuotaForOrigin) ProtoReq() string { return "Storage.overrideQuotaForOrigin" }

// Call sends the request
func (m StorageOverrideQuotaForOrigin) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageTrackCacheStorageForOrigin Registers origin to be notified when an update occurs to its cache storage list.
type StorageTrackCacheStorageForOrigin struct {
	// Origin Security origin.
	Origin string `json:"origin"`
}

// ProtoReq name
func (m StorageTrackCacheStorageForOrigin) ProtoReq() string {
	return "Storage.trackCacheStorageForOrigin"
}

// Call sends the request
func (m StorageTrackCacheStorageForOrigin) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageTrackCacheStorageForStorageKey Registers storage key to be notified when an update occurs to its cache storage list.
type StorageTrackCacheStorageForStorageKey struct {
	// StorageKey Storage key.
	StorageKey string `json:"storageKey"`
}

// ProtoReq name
func (m StorageTrackCacheStorageForStorageKey) ProtoReq() string {
	return "Storage.trackCacheStorageForStorageKey"
}

// Call sends the request
func (m StorageTrackCacheStorageForStorageKey) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageTrackIndexedDBForOrigin Registers origin to be notified when an update occurs to its IndexedDB.
type StorageTrackIndexedDBForOrigin struct {
	// Origin Security origin.
	Origin string `json:"origin"`
}

// ProtoReq name
func (m StorageTrackIndexedDBForOrigin) ProtoReq() string { return "Storage.trackIndexedDBForOrigin" }

// Call sends the request
func (m StorageTrackIndexedDBForOrigin) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageTrackIndexedDBForStorageKey Registers storage key to be notified when an update occurs to its IndexedDB.
type StorageTrackIndexedDBForStorageKey struct {
	// StorageKey Storage key.
	StorageKey string `json:"storageKey"`
}

// ProtoReq name
func (m StorageTrackIndexedDBForStorageKey) ProtoReq() string {
	return "Storage.trackIndexedDBForStorageKey"
}

// Call sends the request
func (m StorageTrackIndexedDBForStorageKey) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageUntrackCacheStorageForOrigin Unregisters origin from receiving notifications for cache storage.
type StorageUntrackCacheStorageForOrigin struct {
	// Origin Security origin.
	Origin string `json:"origin"`
}

// ProtoReq name
func (m StorageUntrackCacheStorageForOrigin) ProtoReq() string {
	return "Storage.untrackCacheStorageForOrigin"
}

// Call sends the request
func (m StorageUntrackCacheStorageForOrigin) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageUntrackCacheStorageForStorageKey Unregisters storage key from receiving notifications for cache storage.
type StorageUntrackCacheStorageForStorageKey struct {
	// StorageKey Storage key.
	StorageKey string `json:"storageKey"`
}

// ProtoReq name
func (m StorageUntrackCacheStorageForStorageKey) ProtoReq() string {
	return "Storage.untrackCacheStorageForStorageKey"
}

// Call sends the request
func (m StorageUntrackCacheStorageForStorageKey) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageUntrackIndexedDBForOrigin Unregisters origin from receiving notifications for IndexedDB.
type StorageUntrackIndexedDBForOrigin struct {
	// Origin Security origin.
	Origin string `json:"origin"`
}

// ProtoReq name
func (m StorageUntrackIndexedDBForOrigin) ProtoReq() string {
	return "Storage.untrackIndexedDBForOrigin"
}

// Call sends the request
func (m StorageUntrackIndexedDBForOrigin) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageUntrackIndexedDBForStorageKey Unregisters storage key from receiving notifications for IndexedDB.
type StorageUntrackIndexedDBForStorageKey struct {
	// StorageKey Storage key.
	StorageKey string `json:"storageKey"`
}

// ProtoReq name
func (m StorageUntrackIndexedDBForStorageKey) ProtoReq() string {
	return "Storage.untrackIndexedDBForStorageKey"
}

// Call sends the request
func (m StorageUntrackIndexedDBForStorageKey) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageGetTrustTokens (experimental) Returns the number of stored Trust Tokens per issuer for the
// current browsing context.
type StorageGetTrustTokens struct{}

// ProtoReq name
func (m StorageGetTrustTokens) ProtoReq() string { return "Storage.getTrustTokens" }

// Call the request
func (m StorageGetTrustTokens) Call(c Client) (*StorageGetTrustTokensResult, error) {
	var res StorageGetTrustTokensResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetTrustTokensResult (experimental) ...
type StorageGetTrustTokensResult struct {
	// Tokens ...
	Tokens []*StorageTrustTokens `json:"tokens"`
}

// StorageClearTrustTokens (experimental) Removes all Trust Tokens issued by the provided issuerOrigin.
// Leaves other stored data, including the issuer's Redemption Records, intact.
type StorageClearTrustTokens struct {
	// IssuerOrigin ...
	IssuerOrigin string `json:"issuerOrigin"`
}

// ProtoReq name
func (m StorageClearTrustTokens) ProtoReq() string { return "Storage.clearTrustTokens" }

// Call the request
func (m StorageClearTrustTokens) Call(c Client) (*StorageClearTrustTokensResult, error) {
	var res StorageClearTrustTokensResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageClearTrustTokensResult (experimental) ...
type StorageClearTrustTokensResult struct {
	// DidDeleteTokens True if any tokens were deleted, false otherwise.
	DidDeleteTokens bool `json:"didDeleteTokens"`
}

// StorageGetInterestGroupDetails (experimental) Gets details for a named interest group.
type StorageGetInterestGroupDetails struct {
	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`

	// Name ...
	Name string `json:"name"`
}

// ProtoReq name
func (m StorageGetInterestGroupDetails) ProtoReq() string { return "Storage.getInterestGroupDetails" }

// Call the request
func (m StorageGetInterestGroupDetails) Call(c Client) (*StorageGetInterestGroupDetailsResult, error) {
	var res StorageGetInterestGroupDetailsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetInterestGroupDetailsResult (experimental) ...
type StorageGetInterestGroupDetailsResult struct {
	// Details This largely corresponds to:
	// https://wicg.github.io/turtledove/#dictdef-generatebidinterestgroup
	// but has absolute expirationTime instead of relative lifetimeMs and
	// also adds joiningOrigin.
	Details map[string]gson.JSON `json:"details"`
}

// StorageSetInterestGroupTracking (experimental) Enables/Disables issuing of interestGroupAccessed events.
type StorageSetInterestGroupTracking struct {
	// Enable ...
	Enable bool `json:"enable"`
}

// ProtoReq name
func (m StorageSetInterestGroupTracking) ProtoReq() string { return "Storage.setInterestGroupTracking" }

// Call sends the request
func (m StorageSetInterestGroupTracking) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageSetInterestGroupAuctionTracking (experimental) Enables/Disables issuing of interestGroupAuctionEventOccurred and
// interestGroupAuctionNetworkRequestCreated.
type StorageSetInterestGroupAuctionTracking struct {
	// Enable ...
	Enable bool `json:"enable"`
}

// ProtoReq name
func (m StorageSetInterestGroupAuctionTracking) ProtoReq() string {
	return "Storage.setInterestGroupAuctionTracking"
}

// Call sends the request
func (m StorageSetInterestGroupAuctionTracking) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageGetSharedStorageMetadata (experimental) Gets metadata for an origin's shared storage.
type StorageGetSharedStorageMetadata struct {
	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`
}

// ProtoReq name
func (m StorageGetSharedStorageMetadata) ProtoReq() string { return "Storage.getSharedStorageMetadata" }

// Call the request
func (m StorageGetSharedStorageMetadata) Call(c Client) (*StorageGetSharedStorageMetadataResult, error) {
	var res StorageGetSharedStorageMetadataResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetSharedStorageMetadataResult (experimental) ...
type StorageGetSharedStorageMetadataResult struct {
	// Metadata ...
	Metadata *StorageSharedStorageMetadata `json:"metadata"`
}

// StorageGetSharedStorageEntries (experimental) Gets the entries in an given origin's shared storage.
type StorageGetSharedStorageEntries struct {
	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`
}

// ProtoReq name
func (m StorageGetSharedStorageEntries) ProtoReq() string { return "Storage.getSharedStorageEntries" }

// Call the request
func (m StorageGetSharedStorageEntries) Call(c Client) (*StorageGetSharedStorageEntriesResult, error) {
	var res StorageGetSharedStorageEntriesResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetSharedStorageEntriesResult (experimental) ...
type StorageGetSharedStorageEntriesResult struct {
	// Entries ...
	Entries []*StorageSharedStorageEntry `json:"entries"`
}

// StorageSetSharedStorageEntry (experimental) Sets entry with `key` and `value` for a given origin's shared storage.
type StorageSetSharedStorageEntry struct {
	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`

	// Key ...
	Key string `json:"key"`

	// Value ...
	Value string `json:"value"`

	// IgnoreIfPresent (optional) If `ignoreIfPresent` is included and true, then only sets the entry if
	// `key` doesn't already exist.
	IgnoreIfPresent bool `json:"ignoreIfPresent,omitempty"`
}

// ProtoReq name
func (m StorageSetSharedStorageEntry) ProtoReq() string { return "Storage.setSharedStorageEntry" }

// Call sends the request
func (m StorageSetSharedStorageEntry) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageDeleteSharedStorageEntry (experimental) Deletes entry for `key` (if it exists) for a given origin's shared storage.
type StorageDeleteSharedStorageEntry struct {
	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`

	// Key ...
	Key string `json:"key"`
}

// ProtoReq name
func (m StorageDeleteSharedStorageEntry) ProtoReq() string { return "Storage.deleteSharedStorageEntry" }

// Call sends the request
func (m StorageDeleteSharedStorageEntry) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageClearSharedStorageEntries (experimental) Clears all entries for a given origin's shared storage.
type StorageClearSharedStorageEntries struct {
	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`
}

// ProtoReq name
func (m StorageClearSharedStorageEntries) ProtoReq() string {
	return "Storage.clearSharedStorageEntries"
}

// Call sends the request
func (m StorageClearSharedStorageEntries) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageResetSharedStorageBudget (experimental) Resets the budget for `ownerOrigin` by clearing all budget withdrawals.
type StorageResetSharedStorageBudget struct {
	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`
}

// ProtoReq name
func (m StorageResetSharedStorageBudget) ProtoReq() string { return "Storage.resetSharedStorageBudget" }

// Call sends the request
func (m StorageResetSharedStorageBudget) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageSetSharedStorageTracking (experimental) Enables/disables issuing of sharedStorageAccessed events.
type StorageSetSharedStorageTracking struct {
	// Enable ...
	Enable bool `json:"enable"`
}

// ProtoReq name
func (m StorageSetSharedStorageTracking) ProtoReq() string { return "Storage.setSharedStorageTracking" }

// Call sends the request
func (m StorageSetSharedStorageTracking) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageSetStorageBucketTracking (experimental) Set tracking for a storage key's buckets.
type StorageSetStorageBucketTracking struct {
	// StorageKey ...
	StorageKey string `json:"storageKey"`

	// Enable ...
	Enable bool `json:"enable"`
}

// ProtoReq name
func (m StorageSetStorageBucketTracking) ProtoReq() string { return "Storage.setStorageBucketTracking" }

// Call sends the request
func (m StorageSetStorageBucketTracking) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageDeleteStorageBucket (experimental) Deletes the Storage Bucket with the given storage key and bucket name.
type StorageDeleteStorageBucket struct {
	// Bucket ...
	Bucket *StorageStorageBucket `json:"bucket"`
}

// ProtoReq name
func (m StorageDeleteStorageBucket) ProtoReq() string { return "Storage.deleteStorageBucket" }

// Call sends the request
func (m StorageDeleteStorageBucket) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageRunBounceTrackingMitigations (experimental) Deletes state for sites identified as potential bounce trackers, immediately.
type StorageRunBounceTrackingMitigations struct{}

// ProtoReq name
func (m StorageRunBounceTrackingMitigations) ProtoReq() string {
	return "Storage.runBounceTrackingMitigations"
}

// Call the request
func (m StorageRunBounceTrackingMitigations) Call(c Client) (*StorageRunBounceTrackingMitigationsResult, error) {
	var res StorageRunBounceTrackingMitigationsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageRunBounceTrackingMitigationsResult (experimental) ...
type StorageRunBounceTrackingMitigationsResult struct {
	// DeletedSites ...
	DeletedSites []string `json:"deletedSites"`
}

// StorageGetRelatedWebsiteSets (experimental) Returns the effective Related Website Sets in use by this profile for the browser
// session. The effective Related Website Sets will not change during a browser session.
type StorageGetRelatedWebsiteSets struct{}

// ProtoReq name
func (m StorageGetRelatedWebsiteSets) ProtoReq() string { return "Storage.getRelatedWebsiteSets" }

// Call the request
func (m StorageGetRelatedWebsiteSets) Call(c Client) (*StorageGetRelatedWebsiteSetsResult, error) {
	var res StorageGetRelatedWebsiteSetsResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// StorageGetRelatedWebsiteSetsResult (experimental) ...
type StorageGetRelatedWebsiteSetsResult struct {
	// Sets ...
	Sets []*StorageRelatedWebsiteSet `json:"sets"`
}

// StorageSetProtectedAudienceKAnonymity ...
type StorageSetProtectedAudienceKAnonymity struct {
	// Owner ...
	Owner string `json:"owner"`

	// Name ...
	Name string `json:"name"`

	// Hashes ...
	Hashes [][]byte `json:"hashes"`
}

// ProtoReq name
func (m StorageSetProtectedAudienceKAnonymity) ProtoReq() string {
	return "Storage.setProtectedAudienceKAnonymity"
}

// Call sends the request
func (m StorageSetProtectedAudienceKAnonymity) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// StorageCacheStorageContentUpdated A cache's contents have been modified.
type StorageCacheStorageContentUpdated struct {
	// Origin to update.
	Origin string `json:"origin"`

	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`

	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`

	// CacheName Name of cache in origin.
	CacheName string `json:"cacheName"`
}

// ProtoEvent name
func (evt StorageCacheStorageContentUpdated) ProtoEvent() string {
	return "Storage.cacheStorageContentUpdated"
}

// StorageCacheStorageListUpdated A cache has been added/deleted.
type StorageCacheStorageListUpdated struct {
	// Origin to update.
	Origin string `json:"origin"`

	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`

	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`
}

// ProtoEvent name
func (evt StorageCacheStorageListUpdated) ProtoEvent() string {
	return "Storage.cacheStorageListUpdated"
}

// StorageIndexedDBContentUpdated The origin's IndexedDB object store has been modified.
type StorageIndexedDBContentUpdated struct {
	// Origin to update.
	Origin string `json:"origin"`

	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`

	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`

	// DatabaseName Database to update.
	DatabaseName string `json:"databaseName"`

	// ObjectStoreName ObjectStore to update.
	ObjectStoreName string `json:"objectStoreName"`
}

// ProtoEvent name
func (evt StorageIndexedDBContentUpdated) ProtoEvent() string {
	return "Storage.indexedDBContentUpdated"
}

// StorageIndexedDBListUpdated The origin's IndexedDB database list has been modified.
type StorageIndexedDBListUpdated struct {
	// Origin to update.
	Origin string `json:"origin"`

	// StorageKey Storage key to update.
	StorageKey string `json:"storageKey"`

	// BucketID Storage bucket to update.
	BucketID string `json:"bucketId"`
}

// ProtoEvent name
func (evt StorageIndexedDBListUpdated) ProtoEvent() string {
	return "Storage.indexedDBListUpdated"
}

// StorageInterestGroupAccessed One of the interest groups was accessed. Note that these events are global
// to all targets sharing an interest group store.
type StorageInterestGroupAccessed struct {
	// AccessTime ...
	AccessTime TimeSinceEpoch `json:"accessTime"`

	// Type ...
	Type StorageInterestGroupAccessType `json:"type"`

	// OwnerOrigin ...
	OwnerOrigin string `json:"ownerOrigin"`

	// Name ...
	Name string `json:"name"`

	// ComponentSellerOrigin (optional) For topLevelBid/topLevelAdditionalBid, and when appropriate,
	// win and additionalBidWin
	ComponentSellerOrigin string `json:"componentSellerOrigin,omitempty"`

	// Bid (optional) For bid or somethingBid event, if done locally and not on a server.
	Bid *float64 `json:"bid,omitempty"`

	// BidCurrency (optional) ...
	BidCurrency string `json:"bidCurrency,omitempty"`

	// UniqueAuctionID (optional) For non-global events --- links to interestGroupAuctionEvent
	UniqueAuctionID StorageInterestGroupAuctionID `json:"uniqueAuctionId,omitempty"`
}

// ProtoEvent name
func (evt StorageInterestGroupAccessed) ProtoEvent() string {
	return "Storage.interestGroupAccessed"
}

// StorageInterestGroupAuctionEventOccurred An auction involving interest groups is taking place. These events are
// target-specific.
type StorageInterestGroupAuctionEventOccurred struct {
	// EventTime ...
	EventTime TimeSinceEpoch `json:"eventTime"`

	// Type ...
	Type StorageInterestGroupAuctionEventType `json:"type"`

	// UniqueAuctionID ...
	UniqueAuctionID StorageInterestGroupAuctionID `json:"uniqueAuctionId"`

	// ParentAuctionID (optional) Set for child auctions.
	ParentAuctionID StorageInterestGroupAuctionID `json:"parentAuctionId,omitempty"`

	// AuctionConfig (optional) Set for started and configResolved
	AuctionConfig map[string]gson.JSON `json:"auctionConfig,omitempty"`
}

// ProtoEvent name
func (evt StorageInterestGroupAuctionEventOccurred) ProtoEvent() string {
	return "Storage.interestGroupAuctionEventOccurred"
}

// StorageInterestGroupAuctionNetworkRequestCreated Specifies which auctions a particular network fetch may be related to, and
// in what role. Note that it is not ordered with respect to
// Network.requestWillBeSent (but will happen before loadingFinished
// loadingFailed).
type StorageInterestGroupAuctionNetworkRequestCreated struct {
	// Type ...
	Type StorageInterestGroupAuctionFetchType `json:"type"`

	// RequestID ...
	RequestID NetworkRequestID `json:"requestId"`

	// Auctions This is the set of the auctions using the worklet that issued this
	// request.  In the case of trusted signals, it's possible that only some of
	// them actually care about the keys being queried.
	Auctions []StorageInterestGroupAuctionID `json:"auctions"`
}

// ProtoEvent name
func (evt StorageInterestGroupAuctionNetworkRequestCreated) ProtoEvent() string {
	return "Storage.interestGroupAuctionNetworkRequestCreated"
}

// StorageSharedStorageAccessed Shared storage was accessed by the associated page.
// The following parameters are included in all events.
type StorageSharedStorageAccessed struct {
	// AccessTime Time of the access.
	AccessTime TimeSinceEpoch `json:"accessTime"`

	// Scope Enum value indicating the access scope.
	Scope StorageSharedStorageAccessScope `json:"scope"`

	// Method Enum value indicating the Shared Storage API method invoked.
	Method StorageSharedStorageAccessMethod `json:"method"`

	// MainFrameID DevTools Frame Token for the primary frame tree's root.
	MainFrameID PageFrameID `json:"mainFrameId"`

	// OwnerOrigin Serialization of the origin owning the Shared Storage data.
	OwnerOrigin string `json:"ownerOrigin"`

	// OwnerSite Serialization of the site owning the Shared Storage data.
	OwnerSite string `json:"ownerSite"`

	// Params The sub-parameters wrapped by `params` are all optional and their
	// presence/absence depends on `type`.
	Params *StorageSharedStorageAccessParams `json:"params"`
}

// ProtoEvent name
func (evt StorageSharedStorageAccessed) ProtoEvent() string {
	return "Storage.sharedStorageAccessed"
}

// StorageSharedStorageWorkletOperationExecutionFinished A shared storage run or selectURL operation finished its execution.
// The following parameters are included in all events.
type StorageSharedStorageWorkletOperationExecutionFinished struct {
	// FinishedTime Time that the operation finished.
	FinishedTime TimeSinceEpoch `json:"finishedTime"`

	// ExecutionTime Time, in microseconds, from start of shared storage JS API call until
	// end of operation execution in the worklet.
	ExecutionTime int `json:"executionTime"`

	// Method Enum value indicating the Shared Storage API method invoked.
	Method StorageSharedStorageAccessMethod `json:"method"`

	// OperationID ID of the operation call.
	OperationID string `json:"operationId"`

	// WorkletTargetID Hex representation of the DevTools token used as the TargetID for the
	// associated shared storage worklet.
	WorkletTargetID TargetTargetID `json:"workletTargetId"`

	// MainFrameID DevTools Frame Token for the primary frame tree's root.
	MainFrameID PageFrameID `json:"mainFrameId"`

	// OwnerOrigin Serialization of the origin owning the Shared Storage data.
	OwnerOrigin string `json:"ownerOrigin"`
}

// ProtoEvent name
func (evt StorageSharedStorageWorkletOperationExecutionFinished) ProtoEvent() string {
	return "Storage.sharedStorageWorkletOperationExecutionFinished"
}

// StorageStorageBucketCreatedOrUpdated ...
type StorageStorageBucketCreatedOrUpdated struct {
	// BucketInfo ...
	BucketInfo *StorageStorageBucketInfo `json:"bucketInfo"`
}

// ProtoEvent name
func (evt StorageStorageBucketCreatedOrUpdated) ProtoEvent() string {
	return "Storage.storageBucketCreatedOrUpdated"
}

// StorageStorageBucketDeleted ...
type StorageStorageBucketDeleted struct {
	// BucketID ...
	BucketID string `json:"bucketId"`
}

// ProtoEvent name
func (evt StorageStorageBucketDeleted) ProtoEvent() string {
	return "Storage.storageBucketDeleted"
}
