// This file is generated by "./lib/proto/generate"

package proto

import (
	"github.com/ysmood/gson"
)

/*

WebMCP

*/

// WebMCPAnnotation Tool annotations
type WebMCPAnnotation struct {
	// ReadOnly (optional) A hint indicating that the tool does not modify any state.
	ReadOnly bool `json:"readOnly,omitempty"`

	// UntrustedContent (optional) A hint indicating that the tool output may contain untrusted content, ex: UGC, 3rd party data.
	UntrustedContent bool `json:"untrustedContent,omitempty"`

	// Autosubmit (optional) If the declarative tool was declared with the autosubmit attribute.
	Autosubmit bool `json:"autosubmit,omitempty"`
}

// WebMCPInvocationStatus Represents the status of a tool invocation.
type WebMCPInvocationStatus string

const (
	// WebMCPInvocationStatusCompleted enum const
	WebMCPInvocationStatusCompleted WebMCPInvocationStatus = "Completed"

	// WebMCPInvocationStatusCanceled enum const
	WebMCPInvocationStatusCanceled WebMCPInvocationStatus = "Canceled"

	// WebMCPInvocationStatusError enum const
	WebMCPInvocationStatusError WebMCPInvocationStatus = "Error"
)

// WebMCPTool Definition of a tool that can be invoked.
type WebMCPTool struct {
	// Name Tool name.
	Name string `json:"name"`

	// Description Tool description.
	Description string `json:"description"`

	// InputSchema (optional) Schema for the tool's input parameters.
	InputSchema map[string]gson.JSON `json:"inputSchema,omitempty"`

	// Annotations (optional) Optional annotations for the tool.
	Annotations *WebMCPAnnotation `json:"annotations,omitempty"`

	// FrameID Frame identifier associated with the tool registration.
	FrameID PageFrameID `json:"frameId"`

	// BackendNodeID (optional) Optional node ID for declarative tools.
	BackendNodeID DOMBackendNodeID `json:"backendNodeId,omitempty"`

	// StackTrace (optional) The stack trace at the time of the registration.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
}

// WebMCPRemovedTool Definition of a tool that was removed.
type WebMCPRemovedTool struct {
	// Name Tool name.
	Name string `json:"name"`

	// FrameID Frame identifier associated with the tool registration.
	FrameID PageFrameID `json:"frameId"`
}

// WebMCPEnable Enables the WebMCP domain, allowing events to be sent. Enabling the domain will trigger a toolsAdded event for
// all currently registered tools.
type WebMCPEnable struct{}

// ProtoReq name
func (m WebMCPEnable) ProtoReq() string { return "WebMCP.enable" }

// Call sends the request
func (m WebMCPEnable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// WebMCPDisable Disables the WebMCP domain.
type WebMCPDisable struct{}

// ProtoReq name
func (m WebMCPDisable) ProtoReq() string { return "WebMCP.disable" }

// Call sends the request
func (m WebMCPDisable) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// WebMCPInvokeTool Invokes a registered tool.
type WebMCPInvokeTool struct {
	// FrameID Frame in which to invoke the tool.
	FrameID PageFrameID `json:"frameId"`

	// ToolName Name of the tool to invoke.
	ToolName string `json:"toolName"`

	// Input parameters for the tool, matching the tool's inputSchema.
	Input map[string]gson.JSON `json:"input"`
}

// ProtoReq name
func (m WebMCPInvokeTool) ProtoReq() string { return "WebMCP.invokeTool" }

// Call the request
func (m WebMCPInvokeTool) Call(c Client) (*WebMCPInvokeToolResult, error) {
	var res WebMCPInvokeToolResult
	return &res, call(m.ProtoReq(), m, &res, c)
}

// WebMCPInvokeToolResult ...
type WebMCPInvokeToolResult struct {
	// InvocationID Unique identifier for this invocation. Response is sent before tool events.
	InvocationID string `json:"invocationId"`
}

// WebMCPCancelInvocation Cancels a pending tool invocation.
type WebMCPCancelInvocation struct {
	// InvocationID Invocation identifier to cancel.
	InvocationID string `json:"invocationId"`
}

// ProtoReq name
func (m WebMCPCancelInvocation) ProtoReq() string { return "WebMCP.cancelInvocation" }

// Call sends the request
func (m WebMCPCancelInvocation) Call(c Client) error {
	return call(m.ProtoReq(), m, nil, c)
}

// WebMCPToolsAdded Event fired when new tools are added.
type WebMCPToolsAdded struct {
	// Tools Array of tools that were added.
	Tools []*WebMCPTool `json:"tools"`
}

// ProtoEvent name
func (evt WebMCPToolsAdded) ProtoEvent() string {
	return "WebMCP.toolsAdded"
}

// WebMCPToolsRemoved Event fired when tools are removed.
type WebMCPToolsRemoved struct {
	// Tools Array of tools that were removed.
	Tools []*WebMCPRemovedTool `json:"tools"`
}

// ProtoEvent name
func (evt WebMCPToolsRemoved) ProtoEvent() string {
	return "WebMCP.toolsRemoved"
}

// WebMCPToolInvoked Event fired when a tool invocation starts.
type WebMCPToolInvoked struct {
	// ToolName Name of the tool to invoke.
	ToolName string `json:"toolName"`

	// FrameID Frame id
	FrameID PageFrameID `json:"frameId"`

	// InvocationID Invocation identifier.
	InvocationID string `json:"invocationId"`

	// Input The input parameters used for the invocation.
	Input string `json:"input"`
}

// ProtoEvent name
func (evt WebMCPToolInvoked) ProtoEvent() string {
	return "WebMCP.toolInvoked"
}

// WebMCPToolResponded Event fired when a tool invocation completes or fails.
type WebMCPToolResponded struct {
	// InvocationID Invocation identifier.
	InvocationID string `json:"invocationId"`

	// Status of the invocation.
	Status WebMCPInvocationStatus `json:"status"`

	// Output (optional) Output or error delivered as delivered to the agent. Missing if `status` is anything other than Completed.
	// Note: The output is untrusted and poses a prompt injection risk. Clients should treat this as potentially malicious user input.
	Output gson.JSON `json:"output,omitempty"`

	// ErrorText (optional) Error text for protocol users.
	ErrorText string `json:"errorText,omitempty"`

	// Exception (optional) The exception object, if the javascript tool threw an error>
	Exception *RuntimeRemoteObject `json:"exception,omitempty"`
}

// ProtoEvent name
func (evt WebMCPToolResponded) ProtoEvent() string {
	return "WebMCP.toolResponded"
}
